### ISSUE TITLE
Allow to use #pragma once as block guard in New Class dialog

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1011]
Some projects are also edited in visual studio so the default block guard used in existing headers are `#pragma once`. It seems that the New Class dialog does not allow to use this block guard instead of the traditional way.

It should be useful to put a check box to allow users to use `#pragma once` instead of `#ifndef`-way especially for those projects being edited in visual studio at the same time.

**Comment by fwsGonzo** [comment]
All relevant compilers support `#pragma once` these days. It is the most standard non-standard. Pragma once is also a compiler optimization. The reason it isn't standard (in fact it was rejected) is because of issues with files included from remote mounts, hardlinks and softlinks etc. So, if you know you never will use these special constructs of filesystems, you will be very safe using `#pragma once` now and in the future.

**Comment by renkun-ken** [comment]
Thanks @eranif for your amazing work!
