### ISSUE TITLE
Add keyboard shortcut to select word under cursor

### ISSUE THREAD

**Issue by joergmerkle1973** [eranif/codelite#1015]
http://forums.codelite.org/viewtopic.php?f=3&t=3152
THANY YOU!

**Comment by eranif** [comment]
Instead of adding new shortcut, I enhanced the functionality of an existing one `Ctrl-K` (`Quick Add Next`)
This only seems natural, `Ctrl-K` by default adds another selection if there is one. So now, it will select the word under the caret (if there is no selection), another hit to `Ctrl-K` will add another selection and so on (so you can edit all selections at once)
