### ISSUE TITLE
Javascript debugger does not show JavaScript Date values

### ISSUE THREAD

**Issue by walkswiththebear** [eranif/codelite#1018]
When looking at a JavaScript Date object, the debugger shows nothing. To see the issue, run this script

showMeDate = new Date(1997, 8, 26);
console.log(showMeDate);

and set a breakpoint on the second line. All you see in the debugger is Date{...}, with no details.

**Comment by eranif** [comment]
Thanks for repoting this.
This bug actually revealed a deeper problem - all objects with values were simply showing `{...}` instead of their actual value

See attached screenshot:

![nodejs-debugger](https://cloud.githubusercontent.com/assets/3677711/11148723/2cad36ac-8a27-11e5-815e-f79bb4dc9f02.png)

**Comment by walkswiththebear** [comment]
Thanks for the quick response, much appreciated!
