### ISSUE TITLE
control-file-has-bad-permissions md5sums 0664 != 0644

### ISSUE THREAD

**Issue by greenthreads** [eranif/codelite#1047]
Platform: Ubuntu 14.0.4.3 LTS, 64 Bit
while installing from the weekly .deb package got the error:

Lintian check results for /tmp/CodeLite-9.0.4-ubuntu-trusty-x86_64.deb:
E: codelite: control-file-has-bad-permissions md5sums 0664 != 0644

seems like a massive ms5checksum issue.

**Comment by eranif** [comment]
This error is caused by `CPack` provided by `CMake` which generates our `.deb` files
We don't have any plans on fixing any of the `.deb` errors for the weekly builds (and there are other errors beside this one). If these errors bothers you, you can switch to use the official released version (9.0) from our repository (the official debs are generated manually without `CPack`)

**Comment by greenthreads** [comment]
Thanks Eran. I use the stable version. Just wanted to check the nightly build and thought should let you know the bug :)
