### ISSUE TITLE
OpenSuse  13.1 wxWidgets 3 cant be installed due to missing/unavailable dependencies

### ISSUE THREAD

**Issue by erbenton** [eranif/codelite#1070]
rpm -Uvh http://repos.codelite.org/wx3.0.2/wx3.0-packages/fedora/3.0.2/20/wx-base-unicode-devel-3.0.2-1.i686.rpm
Retrieving http://repos.codelite.org/wx3.0.2/wx3.0-packages/fedora/3.0.2/20/wx-base-unicode-devel-3.0.2-1.i686.rpm
warning: /var/tmp/rpm-tmp.CWUVxX: Header V4 RSA/SHA1 Signature, key ID 1ac82609: NOKEY
error: Failed dependencies:
        libwx_baseu-3.0.so.0 is needed by wx-base-unicode-devel-3.0.2-1.i686
        libwx_baseu_net-3.0.so.0 is needed by wx-base-unicode-devel-3.0.2-1.i686
        libwx_baseu_xml-3.0.so.0 is needed by wx-base-unicode-devel-3.0.2-1.i686

I cant find the libwx_baseu*3.0 for OpenSuse 13.1 x86_64 anywhere which prevents this upgrade from the old 2.8 that comes standard.

**Comment by dghart** [comment]
Hi,
I'm a bit confused about what you're doing. First, are you really using openSUSE 13.1, rather than a later version?
Second, you seem to be trying to install our unofficial fedora wxWidgets rpms, rather than the openSUSE ones. Is there a reason for this?

Assuming you do use 13.1, for which we no longer provide packages, you have the following choices:
1) Try installing the current CodeLite 9.0 13.**2** rpm (see http://codelite.org/LiteEditor/Repositories#toc2) which itself contains the correct wxWidgets libs. I've not tested this in 13.1, so no guarantees.
2) Install the rpm of the last CodeLite version, 6.1, that we provide for openSUSE 13.1; see [this archived page](http://codelite.org/LiteEditor/Repositories61#toc2). This too contains its own wxWidgets libs.
3) Build CodeLite from source, either using the [9.0 source rpm](http://repos.codelite.org/rpms/suse/codelite-9.0-2.suse.src.rpm) or the tarball or git. This time you *will* need to install  our [unofficial wxWidgets libs](http://codelite.org/LiteEditor/WxWidgets30Binaries#toc3).

Please let us know how you get on.

Regards,
David

**Comment by erbenton** [comment]
Hi,  Yeh, I'm really on 13.1, I tried a fresh install of 13.2 a couple 
of weeks ago but IMHO its not ready for prime time and didnt sit well 
with me. I'll try the 13.2 rpm but i suspect it will have a lot of 
required dependencies. In some cases you get into a wind-up where you 
can never really satisfy them all without installing a ton of otherwise 
unused deps, as one leads to more and then to more etc etc. I'm half 
tempted to move to Fedora, need to look into that some as I am not 
familiar with it at all
What I'm really after is a way to get wxWidgets-devel 3.0 or better 
installed in 13.1 so I  can build the latest version of boinc.

Thanks,
Eric Benton
Olympia WA
KG7RYU

**Comment by dghart** [comment]
Hi Eric,
>13.1, I tried a fresh install of 13.2 a couple of weeks ago but IMHO its not ready for prime time

So the latest, 42.1, doesn't stand a chance ;)

>What I'm really after is a way to get wxWidgets-devel 3.0 or better installed in 13.1

OK, that's easy: just use our [13.1 unofficial wxWidgets 3.0.2 rpms](http://codelite.org/LiteEditor/WxWidgets30Binaries#toc3); I can't be more specific as I don't know if you're 32 or 64 bit.

Regards,
David

**Comment by erbenton** [comment]
I'm on x86_64 - are those development rrpms?

Thanks,
Eric Benton
Olympia WA
KG7RYU
Buy a man a beer and he will waste an hour.......
Teach that man how to brew beer and he will waste a lifetime.
You're a funny guy Sully, I like you. That's why I'm going to kill you last.
Turkey Creek Jack Johnson: Nobody move!
Doc Holliday: Nonsense. By all means, move.
*Each generation must pass liberty on to the next generation.
   If we fail, that is on us.
If I didn't drink so much, I'd really be dangerous.
     So, how about you buy me another, just to be on the safe side?

**Comment by dghart** [comment]
Yes, they're the ones I use for building CodeLite!

Regards,
David

**Comment by erbenton** [comment]
Ok, I'll give it a shot - thanks a lot for your help!

Thanks,
Eric Benton
Olympia WA
KG7RYU
Buy a man a beer and he will waste an hour.......
Teach that man how to brew beer and he will waste a lifetime.
You're a funny guy Sully, I like you. That's why I'm going to kill you last.
Turkey Creek Jack Johnson: Nobody move!
Doc Holliday: Nonsense. By all means, move.
*Each generation must pass liberty on to the next generation.
   If we fail, that is on us.
If I didn't drink so much, I'd really be dangerous.
     So, how about you buy me another, just to be on the safe side?
