### ISSUE TITLE
[Core] Toggle All Panes & checked other Pane

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#1088]
System: Linux anatooly 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
CL version: 9.0.7
Workspace: PHP Project

View - Workspace Pane checked.
When click View - Toggle All Panes, all workspace panes is hidden but checkbox on View - Workspace Pane is true. Then in future that problem if I click View - Workspace Pane it show, but unchecked, and after restart apps not showing.

**Comment by eranif** [comment]
Sorry, due to resource limitation - this won't be fixed unless someone else fixes it with a pull request

**Comment by anatooly** [comment]
If you close all task who know in future of this problem?

**Comment by eranif** [comment]
Usually, I close the tasks that I am not going to fix/implement. If someone else finds it annoying - he will fix this, he does not need a bug report for this.

Since only me and sometimes David are fixing bugs reported on the issue tracker, I don't see the point of keeping a bug which we both don't plan on fixing opened

**Comment by anatooly** [comment]
I'm understood, thank you.
