### ISSUE TITLE
No dark theme!

### ISSUE THREAD

**Issue by achlubek** [eranif/codelite#1122]
Oh my god I love that IDE, but my** eyes burn** down when I sit 19 hours straight making C code, staring at all those super **bright borders**! 
Guys do you even code at **night**? Why no full dark theme yet?
That's a**_ blocker issue_**!

Kind regards,
Me

**Comment by genusistimelord** [comment]
I agree that it would be nice to have the ability to change the border and colors of the widgets. it would make it more Visual studios like then. and i bet more people from that area would use codelite over VS if you did add this feature in.

**Comment by eranif** [comment]
@achlubek  can you post a screenshot on how your development looks like? (in CodeLite)

**Comment by genusistimelord** [comment]
technically the code inner window is dark but the outer stuff is not which tends to not work well with a dark environment or dark internal screen. 
http://i.imgur.com/jZbhWe0.png

**Comment by eranif** [comment]
The problem is withe GUI framework that we use (wxWidgets)
It uses the native controls, i.e. they take their colours from the system settings

btw, the most annoying thing in this picture is not the gray areas, but rather the white background of the tree view - which can altered in CodeLite.

There are few more things you can do to improve CodeLite appearance:
* ` settings->colours and fonts->general->global background colour` and set the global background colour to gray
*  Hide the docking windows captions `settings->preferences->windows & tabs->hide docking windows captions`
* Hide the toolbar: `view->show toolbar`
* Use `Ctrl-M` to hide all non essential windows during coding...
Attached is CodeLite on my MacBook
<img width="1010" alt="screen shot 2016-02-04 at 7 28 00 am" src="https://cloud.githubusercontent.com/assets/3677711/12806722/375b685a-cb11-11e5-9eb1-9915cd19fe50.png">

**Comment by genusistimelord** [comment]
OK thank you I will let him know though I'm surprised wxWidgets doesn't have a method to allow you to set your own colors. I thought it did... Anyways thank you and also I myself have been working on a GUI made in pure C. thought its new so its no where near what wxWidgets has yet.

**Comment by eranif** [comment]
@genusistimelord (Doctor Who?) all wxWidgets widgets have a method `SetBackgroundColour()` however, it does not work well with various controls (such as wxCheckBox, wxCombxBox and others)

**Comment by genusistimelord** [comment]
Edit i figured out how to change the toolbar to be a darker color.
Settings->Preferences->Misc->Use Native Toolbar   
Disable that and it then looks like.

http://i.imgur.com/Iin0W81.png

**Comment by eranif** [comment]
This is because when you disable the native toolbar, I am using wxAuiToolBar which is a custom toolbar
For this toolbar, I have a complete control on its content and I can draw (and I am) the background colour as I wish...

**Comment by genusistimelord** [comment]
I figured that out and maybe that something that could have been added to the above to make it look better =]. anyways i like the toolbar just did not like the previous colors and i did not know disabling that would change it to become darker. Regardless thank you for your time.
