### ISSUE TITLE
[Design Request] Ability to remove Custom Templates from Project Types

### ISSUE THREAD

**Issue by Yekyaa-** [eranif/codelite#1146]
Right-clicking a project allows for the option of "Save As Template...", however, there's no simple way to remove extra templates via the IDE itself. I had to go through the installation folder on my hard drive to find where they are stored in order to manually delete them. Is there a possibility of giving us an option to "Manage Project Templates"?

**Comment by supermirtillo** [comment]
I would like that too

**Comment by xaviercho** [comment]
has this been fixed?

**Comment by xaviercho** [comment]
I successfully deleted a CodeLite project template that I created earlier as follows:

On my machine, the project template are stored in the following folder:

C:\Users\username\AppData\Roaming\codelite\templates\projects


Make sure to change your username to whatever it is on your PC.

1. Exit CodeLite 

2.Using File Explorer, go to the directory on your PC where the project templates are stored. This directory maybe hidden in file explorer, but you can type in the directory path.

3. Look for the file to delete and delete it.

4. Restart CodeLite and the project template should no longer appear.

**not my solution this is from a udemy course by "frank j." , just paying my respects since this is the most viewed on google I thought to post it here.

**Comment by StoIos** [comment]
As an addition to the above answer. On Linux the location of these template files is in a hidden folder.

/home/<user name>/.codelite/templates/projects/

the templates will be saved as .project files
