### ISSUE TITLE
Removing files from project is problematic and dangerous

### ISSUE THREAD

**Issue by bigangrydog** [eranif/codelite#1152]
When right-clicking on a file in the project and selecting "Remove", the user is first asked to confirm and then asked whether they want to remove the file on disk. There are two problems here:

1. It is easy to click-thru, resulting the file accidently being deleted on disk.

2. Selecting n files (which can be many) and clicking "remove" results in the user having to face 2n dialog confirmations (i.e. 2 confirmations for each file). The chances of accidently deleting the file on disk are high with this.

A possible solution would be to have to 2 context menus as follows:

* Remove (removes file only in the project)
* Delete on Disk (removes and deletes on disk)

For both, there should be a single confirmation pertaining to either the selected filename, or if multiple files are selected, it could say "Remove/Delete selected files?".

Codelite version: 9.1.1

**Comment by eranif** [comment]
> It is easy to click-thru, resulting the file accidently being deleted on disk.

Remove by its nature is something that requires from the user to stop for a second and pay attention to the prompting dialog

> Selecting n files (which can be many) and clicking "remove" results in the user having to face 2n 

Not really, you have an option to "Remember my answer" checkbox which will prevent that question being presented for other files (this checkbox is not remembered next time you try to delete file from the file view)

>  A possible solution would be to have to 2 context menus as follows:
> 
> Remove (removes file only in the project)
> Delete on Disk (removes and deletes on disk)

What's keeping me from making the same mistake here and clicking 'Delete' instead of 'Remove'?

I am not going to fix this, as I really don't see the problem with the current implementation.
