### ISSUE TITLE
SFTP output tab missing 

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1175]
Version 9.1.3 (compared to 9.1.2) on OS X is missing SFTP output window tab in a PHP Workspace - automatic uploads don't seem to work anymore either.

**Comment by Kanimies** [comment]
Downgrading back to 9.1.2 did not bring back the SFTP output pane.

**Comment by eranif** [comment]
The tab name was renamed. And probably the 'layout' system of CodeLite does not display it because it is considered 'new'

The new name is "SFTP Log"
To re-enable it you will first need to enable the "Docking windows captions" from
Preferences->Windows & Tabs->Hide docking windows captions

Next, on the "output" pane, you will have a 3 dots button - click it and select the "SFTP Log" tab
