### ISSUE TITLE
Assigning keyboard shortcuts clumsy

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1183]
When assigning keyboard shortcuts, you should not have to manually check which modifier you want the shortcut to work on, i.e. <char> + Ctrl/Alt/Shift. I don't know how wx handles this, but I think it should be possible to evaluate Ctrl/Alt/Shift as flags from the key event. As most shortcuts (if not all) have at least one modifier, this should be done automatically (check boxes can remain at its place, in case any combinations are not evaluable by hotkey control).

Further, the _'Ctrl-F4' **is already assigned to**: 'Close'_ MessageBox is not very helpful, because you have to navigate back and forth all the time this way. A prompt like _"...  is already assigned to: ... **Delete original assignment?** [Y/N]"_ would increase usability by far.

**Comment by eranif** [comment]
Couple of years ago, this was the case, however, the wx behavior was not working smooth - so we changed to the current one. I don't see this as an issue, since assigning shortcuts is not something you do all time - If you wish, you could create a pull request with the suggested fix (tested on all 3 platforms, GTK is the problematic one)

In CodeLite 9.1.3 you have a "Suggest" button which can show you all un-used keyboard shortcuts
