### ISSUE TITLE
The Build->Run command does not seem to work

### ISSUE THREAD

**Issue by kuiperzone** [eranif/codelite#1220]
Nothing I do seems to generate any output. I am trying to run a console program. Screenshot attached.

Version 9.1.4.

![untitled](https://cloud.githubusercontent.com/assets/17156238/14091595/fdac65f8-f538-11e5-8603-401848948ce9.png)

**Comment by bigangrydog** [comment]
Just noticed that I had the "Project Type" set to "Dynamic Library" (I am using a makefile in any case). However, changing the type to "Executable" makes no difference -- it still won't run.

Does the Execution options handle variables? (Ideally I would like to use these)

Any chance of having a run/debug option on the project context menu?

**Comment by bigangrydog** [comment]
Scrub some of the last remarks. It's working, but there's still an issue. The problem I was having was due to the fact I had several DOS windows open, and the new one wasn't been brought to the front, so I could not see it. This is probably not something to do with Codelite.

However, what I'm really trying to do is run a makefile from a directory relative to the working directory, and run my makefile via a makefile run goal. While I get a DOS window, there's is no output.

So I tried this:

Working dir: E:/dogma/bin
Executable to run: dir

I get a DOS window, but no output!
