### ISSUE TITLE
The find bar just disappears on its own!

### ISSUE THREAD

**Issue by bigangrydog** [eranif/codelite#1223]
The find bar works great except that it just seems to disappear of its own accord. I'm not sure what the rule is -- it appears enigmatic.

I suspect this is deliberate behaviour, the assumption being it "intelligently" decides that the user has finished with it. However, I would like the find bar to stay in place, as I'm actually still wanting to use it. Given that there's an easy to click [X] button, I see no reason why this behaviour would be helpful.

Suggest the find bar stays visible until the user clicks [X].

**Comment by eranif** [comment]
The following will cause the find bar to go away:
* Clicking `Find All` will make it go away
* Clicking `Replace All` will make it go away
* Hitting `ESCAPE` inside the editor will make it go away

I don't plan on changing this... as I find it very useful
If you think it should behave otherwise - please submit a pull request that fixes the current behavior in a configurable manner
