### ISSUE TITLE
Feature request: Custom clang binary for code completion and continuous build

### ISSUE THREAD

**Issue by jamsilva** [eranif/codelite#1245]
I am using CodeLite (9.1.5) for a project that uses the Android NDK and would like to use the clang++ binary that is included with the NDK to get autocompletion to work correctly (for instance, to correctly detect that the \__ANDROID__ macro is defined).

It seems that a previous version supported this feature, as seen in http://codelite.org/LiteEditor/ClangIntegration, but I can't find the "clang path" option anywhere.

**Comment by eranif** [comment]
> it seems that a previous version supported this feature, as seen in

This is not a "previous version", but more of an ancient version (that page was edited 5 years ago)

Since then, the clang code completion has evolved and CodeLite links directly to libclang.dll
What you can do is to replace libclang.dll with the once that was compiled for Android and pray to the gods of zeros and ones that it will work ...
