### ISSUE TITLE
Auto code completion for HTML, CSS and JS needed

### ISSUE THREAD

**Issue by patlecat** [eranif/codelite#1247]
Since you began to offer PHP support, we also need the auto code completion for those files at least, else it's no fun at all. I would really love to use the IDE that is so great for C++ also for my PHP projects!

BTW: I use YiiFramework and Symfony, some support for them would also be greatly appreciated :dancers:

**Comment by eranif** [comment]
Atm, the JS code completion is available for `.js` files but IIRC, it only available if a Node.js is enabled.
Will need to check why... :/

HTML code completion is enabled (in terms of complete closing tags and provide list of all known tags for selection)

CSS is using the word completion plugin (Ctrl-ENTER, which it provides basically same code completion as sublime does: i.e. based on existing words from the open documents)

Can you please reply to each of my comments and respond what is not working for you? (it does for me)
Example files / projects that illustrates the problems + expected behavior

**Comment by patlecat** [comment]
Well I tried to use CodeLite with HTML mainly and there was no autocomplete nor did it create a closing tag automatically.
Btw, something like the Emmet extension would be nice too. Even PHPStorm has it built-in.

**Comment by anatooly** [comment]
@patlecat I ask this question before, like this https://github.com/eranif/codelite/issues/1100
Autocomplete JavaScript work only on Node.Js workspace. Now you need create two project: first only with PHP files & second with only static js/css/html files.

**Comment by AJenbo** [comment]
@eranif would it make sense to seed the word list with standard html tags and css attributes in addition to the file content?
