### ISSUE TITLE
"Reload File" and "Find and Replace" shorcuts conflict

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1249]
Fresh installation of CodeLite 9.1.0 from PPA on Ubuntu x64 15.10.

Trying to press Ctrl-R to invoke "Find and Replace" doesn't work. It seems that Ctrl-R is also assigned to "Reload File" command, which gets executed first. As a workaround, after fresh installation, user needs to go to Keyboard shorcuts menu to resolve this conflict (in my case, just remove Ctrl-R assignment from Reload File command).

Since Ctrl-R shortcut for "Find and Replace" is common to most source code editors, it would be better to change default CodeLite installation settings and remove "Ctrl-R" shortcut from "Reload File" command.

**Comment by mtangoo** [comment]
Its depends. Almost all editors I know use Ctrl+H for replace. But CL have option in settings dialog to assign commands as you want.  I have never used it as I had no need to but worth of checking though

**Comment by yunkot** [comment]
The issue is that the same shortcut is assigned to two commands after installation, which makes it misleading: when you navigate to "Find and Replace", you see that shortcut is "Ctrl-R", but it doesn't actually work. Figuring out why it didn't work was a lucky hunch.

**Comment by eranif** [comment]
The problem is that wxWidgets tries to be "smarter" and when it sees a menu entry with the stock ID wxID_REPLACE it automatically assigns it with the default keyboard shortcut Ctrl-R which causes a conflict with 'Reload File' keyboard shortcut which is also defined to 'Ctrl-R'
The solution is: fix wxWidgets or use a different ID for replace (the latter is easier to fix)

**Comment by eranif** [comment]
See also https://github.com/eranif/codelite/issues/1158
