### ISSUE TITLE
"No executable specified"

### ISSUE THREAD

**Issue by emruiz81** [eranif/codelite#1256]
Hello,

I'm trying to build and run a simple C++ executable from Codelite 9.1.6 under Windows 10 64 bits. The problem is that if you don't manually define the executable to run, it just does nothing in release mode, and it returns a "no executable specified" error. The way to fix this is to manually write the path of the generated excutable in the project settings (parameter "Executable to Run / Debug). 
I think that if this parameter is empty, it should directly use the output executable of the current target.
Thanks in advance for your help!

**Comment by eranif** [comment]
I just created an empty project, build and run it without an issue.
The default value for "Execute to debug / run" is set to `./$(ProjectName)`
While the "Output File" is set to `$(IntermediateDirectory)/$(ProjectName)` this means, that this executable will be debugged / run (tested and works). So unless you changed the settings...

**Comment by lpoujoulat** [comment]
I have the same problem with the codelite bundled in Ubuntu 16.04 64 bits. Created a project with the wizard (wxCrafter), and when running or debugging the executable is not found. Digging a bit, it seems that is searches the executable relative to the home directory and not the intermediate one.

**Comment by eranif** [comment]
Unable to reproduce

**Comment by danielmacho72** [comment]
I had the same issue, it turned out that for me the project was a problem with white spaces in some of the default Windows folders where I had my workspace and projects. 

It was the default C:\Users\<user>\Documents one, where <user> had a white space, so apparently CodeLite not dealing well with such folders. The solution has been to move all workspaces from that folder to C:\CodeLite simple one and then my projects started running properly (Debug and Release)...
