### ISSUE TITLE
[Feature Request] pragma region/endregion for code folding

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1279]
This was introduced in MSVC 2015 and helps to fold arbitrary regions of code. Since CodeLite supports code folding, it would be beneficial to support and understand this pragma type in editor.

The syntax is explained on MSDN: https://msdn.microsoft.com/en-us/library/b6xkz944.aspx

**Comment by eranif** [comment]
The build-in folding comes from `wxStyledTextCtrl` control which is based on [Scintilla](http://scintilla.org)
So, in order to have this, it needs be added to `Scintilla` and then someone needs to port the latest into `wxWidgets` and you will have this in CodeLite :)

In the meantime, you can add user folding blocks:

Fold start point
`//{`
Fold end point:
`//}`
