### ISSUE TITLE
Static functions are classified to "Global Functions and Variables" at Outline pane

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#1304]
This issue could be found at C language project. All of the static functions are classified to global functions. Dose Outline support identify and list local functions and variables? thanks!

**Comment by xuancong84** [comment]
Static functions are intrinsically global functions, because it is compiled as global functions. It is just that the compiler explicitly makes it visible only within the scope of that particular source file. We expect the C language project to classify them as source-file-specific global functions in the future, in order to distinguish them from the standard global functions.

**Comment by Cookfeces** [comment]
@xuancong84 I don't agree that static functions are complied as global functions.At least, if you use gnu gcc to complie a static function, you can found the symbol's attribute is LOCAL when use "readelf -h" to read the output file, and the normal function's attribute is GLOBAL. However, I also think source-file-specific function is a good way to solve this problem, and I very much look forward to seeing this problem is solved in the future ^ ^
