### ISSUE TITLE
Create a portable version!

### ISSUE THREAD

**Issue by Denisov21** [eranif/codelite#1312]

**Comment by RyanSW** [comment]
I created a simple batch file that manually sets the user profile path, app data path, and compiler paths then loads the executable. Realistically, this could also be done with the portable apps launcher. I don't think a portable version is truly necessary, but it would be nice to be able to download the executable files as a zip or tar rather than only a windows installer...

**Comment by eranif** [comment]
This is not something I am going to invest time on it
