### ISSUE TITLE
Git plugin cannot switch project repo

### ISSUE THREAD

**Issue by kipade** [eranif/codelite#1358]
I think, all projects within a workspace should have its own git repo.
But, now, git plugin cannot switch repo directory although I switch to a different project

**Comment by eranif** [comment]
Can you please provide some more information:
- Which workspace? (C++, NodeJS or PHP)
- CodeLite version and OS

**Comment by kipade** [comment]
1. Workspace: C/C++
2. CodeLite: version 9.1.0, Linux 64bit
Thanks

**Comment by eranif** [comment]
From looking at the code, this is the case
If I make another project active, the `git` plugin switches to the project folder.
It does that by searching for `.git` folder in the project path, if it can't find it there, it try its parent

**Comment by kipade** [comment]
So, the problem is.
Here, I set the repo directory to another directory, not the project directory. 
... all the projects within the workspace have no .git directory

**Comment by iwbnwif** [comment]
Same problem here.

I have a git repo (wxFreeChart library) as a subfolder in my workspace. The plugin always reverts to the workspace folder (which has no git repo) when Codelite is first opened.

I can work around it on each session by using the "Set repository path" toolbar button, but it would be good if it could remember the last used path or was configurable somehow. Thanks :)

**Comment by dghart** [comment]
Most or all of this should now be fixed by 995f9f2. As before, CodeLite looks first in the project dir, then in the workspace dir; but if no .git dir is found, it tries the last-used repo path.

Because of that order of attempts, it will fail to use an outside repo if there's also one (presumably belonging to a different project) in the workspace dir. So don't do that ;)  If you find any other failures, please reopen this.
