### ISSUE TITLE
Codelite doesnt show variable data all the time until the source is saved.

### ISSUE THREAD

**Issue by genusistimelord** [eranif/codelite#1371]
When writing a new function the variable data in the functions parameter is not displayed when typing till after the source is saved. Also the variable does not display after writing a new if statement until source saved.

http://i.imgur.com/A5GZgV0.png
http://i.imgur.com/0jicO0D.png

I believe it may be due to the if statement.

**Comment by eranif** [comment]
No, its due to the implementation of the code completion.
The problem is with the code completion cache: CodeLite keeps the function start and end position, when you extend the function beyond its "end" position, the cache "thinks" that the caret is inside the next function (`parse_updates`) so the variable `data` is offered.

When you save the source file, the cache is refreshed and everything works again
Changing this behavior will probably impact the code completion performance (which I really try to keep to the minimum), a possible solution is to add a new plugin to CodeLite which performs auto-save (similar to how Google docs works)

**Comment by eranif** [comment]
A new `Auto Save` plugin as added. Which allows you to setup an automatic file saving
