### ISSUE TITLE
compiler error highlighting

### ISSUE THREAD

**Issue by HackiWimmer** [eranif/codelite#1473]
Hi,
I've lastly switched to Windows 10 64 bit and codelite 9.2.6. Since this update compiler errors are shown on the built outpane as pure text, so they are didn't highlighted in red and the disn't appear as link to the correponding code, but warings did appear correct.

Is there an issue or a trick? Or is there an dependency to the used compiler?

By the way: I'm using mingw-w64/i686-6.2.0-posix-dwarf-rt_v5-rev1/mingw32/bin/g++.exe as compiler.

Many thanks in advance . . .

Cheers
Stefan

![build output pane](https://cloud.githubusercontent.com/assets/21140722/20388065/6e7b82cc-acc3-11e6-835a-1d2186e8591c.jpg)

![settings](https://cloud.githubusercontent.com/assets/21140722/20388137/d7f9de88-acc3-11e6-890f-2ea4ab026aa3.jpg)

**Comment by eranif** [comment]
The problem is that you are using a character `@` which is not included in the valid chars for path by CodeLite.
You can easily change this from:

`Settings->Build Settings->Compilers->YOUR COMPILER->Patterns`
You will see there list of regular expressions for capturing warnings and errors produced by the compiler
Add the `@` to the file name part of the regular expression.

For example, this pattern: 
`^([^ ][a-zA-Z:]{0,2}[ a-zA-Z\.0-9_/\+\-]+ *)(:)([0-9]*)([:0-9]*)(: )((fatal error)|(error)|(undefined reference)|([\t ]*required from))`

Should be something like this:
`^([^ ][a-zA-Z:]{0,2}[ a-zA-Z\.0-9_/\+\-@]+ *)(:)([0-9]*)([:0-9]*)(: )((fatal error)|(error)|(undefined reference)|([\t ]*required from))`

**Comment by HackiWimmer** [comment]
. . . many thanks, now it works!
Cheers
Stefan
