### ISSUE TITLE
Notification: OBS Project building the latest tagged release (10.0) for Fedora and openSUSE.

### ISSUE THREAD

**Issue by fusion809** [eranif/codelite#1502]
Hi,

I thought I'd let yas know I've built the latest tagged CodeLite release for Fedora and openSUSE in my [Open Build Service project](https://build.opensuse.org/package/show/home:fusion809/codelite). It took me over 12 hours and 2 Unix & Linux StackExchange questions ([this one](http://unix.stackexchange.com/questions/334320/how-do-i-fix-this-spec-file-it-keeps-giving-me-sed-errors-yet-the-only-sed-is-l) and [this other one](http://unix.stackexchange.com/questions/334335/fedora-24-how-to-get-the-wx-config-script-detected-in-opensuse-build-service)) but I finally got the Open Build Service to build both Fedora and openSUSE packages. I used the `CL_Fedora.spec` and `CL_SuSE.spec` inside your SRC RPMs (SRPMS) to build it, but it took a lot of modification to combine the two spec files into a single one and get them to build CodeLite 10.0 on the Open Build Service. 

Thanks for your time,
Brenton

**Comment by dghart** [comment]
Hi,

Congratulations on getting it to build, especially with a combined .spec file. 

I'll bookmark this 'issue' so that I can suggest it if anyone asks for other rpms e.g. on #codelite. However bug-tracker issues aren't very visible. A mention on http://codelite.org/forum/ will get a wider audience, either in a standalone thread or as a reply to the 10.0 Announcement thread, expected later today.

Regards,
David
