### ISSUE TITLE
Environment variables dialog does not remember its size

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1523]
Environment variables dialog does not remember its size

CL-10.0.0/ArchLinux-64bit

**Comment by eranif** [comment]
Under Linux there is a long standing opened bug about dialogs keep resizing when using wx's persistence manager class
Until this bug is not fixed in wxWidgets (the dialog size keeps resizing each time you 'show' it)
I am afraid this will not be fixed. Note that this only happens when using Unity, however, CodeLite's code can not tell if it runs under KDE or Unity, so I disabled this for all Linux

**Comment by givanz** [comment]
Hi

Can this option be enabled back for linux or at least provide a configuration flag or checkbox to enable it? 
I'm using xfce and probably there are many linux users that don't use unity and can benefit from this feature.
Windows like `Open Resource ..` have small size defaults and resizing them all the time is annoying.
CodeLite is the best, non bloated and non memory intensive IDE on linux, but little issues like this make it hard to use.

Thank you.
