### ISSUE TITLE
change CMake projects' Working Directory default value

### ISSUE THREAD

**Issue by fcolecumberri** [eranif/codelite#1532]
at this moment, the default value is:
$(WorkspacePath)/build-debug

but should be:
$(ProjectPath)/build-debug

so when executing
cmake ..
the ".." target the corect directory

I don't know if this could just be modified by changing a config file

**Comment by eranif** [comment]
Which CodeLite version are you using?
With the latest, 10.0.1 each project gets its own build folder:
`$(WorkspacePath)/<ProjectName>/`

This is the new design and its not going to change.
The idea is to keep all the build files and output files in a single folder rather than scattered across the file system
