### ISSUE TITLE
The path to source files are broken during debug

### ISSUE THREAD

**Issue by Lyberta** [eranif/codelite#1555]
After updating to CodeLite 10, building my libraries with it and debugging them, it looks like the paths to the source files are incorrect. Instead of the correct paths I get paths starting with "./Build./" which is not where my files are.

**Comment by eranif** [comment]
CodeLite does not "figure" the paths by itself, but rather it accept the path from GDB.
I doubt this issue is related to CodeLite. Please check if you updated other components as well, such as GDB version etc

Please use the forum for further discussion

FYI:
This bug report is rather useless, it is lacking crucial information such as:
* How to reproduce this issue (it clearly does not happen here, otherwise, I would have seen and fix it already)
* Which OS version are you using?
* The build logs + debugger logs

But like I said, please use the forum at https://forums.codelite.org
