### ISSUE TITLE
symbolic link handling

### ISSUE THREAD

**Issue by leventelist** [eranif/codelite#1576]
Codelite has hard time handling symbolic links. If a source file is a symlink, it will delete the link, and create a file from the content it is was pointed to.

**Comment by uffejakobsen** [comment]
It seems that this is still an issue with CL 11.0.0

CL 11.0.0 @ arch linux

**Comment by leventelist** [comment]
@eranif was that fix went to 11.0.0? I haven't tested it yet.

**Comment by dghart** [comment]
I wasn't able to get 'save' to overwrite a symlink. However the current code did fail to save at all when the symlink was relative (it complained about a non-existent permissions problem) and would probably have failed if there was >1 symlink ahead of the real file.

This should now have been fixed by 766d8c7. If you still have problems, please could you explain how to replicate them, or ideally provide a testcase project.
