### ISSUE TITLE
Enum values with the same name as a class get colored as a class

### ISSUE THREAD

**Issue by surafel911** [eranif/codelite#1581]
Just as the title suggests, if I have an enum class value that has the same name as a class, the enum class  value will be colored as if I was referencing the class. 

As you can see here, the "Window" value is shaded green. You know it's supposed to be that way since the namespace and the enum class are colored the same way. But nothing is included in the header file.

![payment](https://cloud.githubusercontent.com/assets/24972439/23584906/1205227c-013d-11e7-80cd-235767615ab3.JPG)

You can see here in the Window class header file that ErrorCode.hpp has not even been included.

![image](https://cloud.githubusercontent.com/assets/24972439/23584914/565f4196-013d-11e7-990f-b22f1ae24a30.png)

Let me know if you need more information.

**Comment by eranif** [comment]
The editor highlight is based on "words" and not context (otherwise, the editor highlight would have consume a lot of CPU and make the editor pretty much useless)

The internal implementation is based on "keywords sets" each set is coloured differently. If two sets contains the same word, the first set colour will "win"

There is nothing we can do about this, this is how the editor component works (http://scintilla.org)
