### ISSUE TITLE
PHP: Refactoring: no option to rename function name

### ISSUE THREAD

**Issue by zestllankesh** [eranif/codelite#1725]
Hi,
I am using CodeLite as PHP IDE. I am using this on OSX.

When I tried to rename name of a function it did not work. I didn't see any option for renaming function name.
I could see options only for class members and local variables

Please help.

I've attached some snapshots which might shed some light on what I am talking about

<img width="808" alt="screen shot 2017-08-23 at 6 38 05 pm" src="https://user-images.githubusercontent.com/16576814/29617355-3f1a8014-8832-11e7-807b-4e2ef1692dd0.png">
<img width="544" alt="screen shot 2017-08-23 at 6 39 39 pm" src="https://user-images.githubusercontent.com/16576814/29617427-7749fb68-8832-11e7-8a22-b69836e8e52c.png">

**Comment by AJenbo** [comment]
Method renaming is currently not supported. Renaming public and protected methods can be tricky since they might be called from outside the file. 

I hope to work any further abilities directly in to code lite as there isn't really an active community around the refactoring Brower that we use for php refactoring. Unfortunately that means that it could be a while before new features like that will be implemented, unless it turns out to be trivial to add to php refactor browser, or anyone else adds it. 

https://github.com/QafooLabs/php-refactoring-browser

**Comment by eranif** [comment]
Since this depends on an external project which is out of our hands, I am closing this issue

**Comment by zestllankesh** [comment]
Sorry for late reply. Got caught up in some other tasks.
Thanks for taking out time to explain this.
It sucks not to have method renaming.
But I do understand your situation.
By the way I love this IDE.
Hope we'll get this feature soon enough :)

I'll study the above mentioned library in my free time.
Can you give me directions as how this library is integrated into CodeLite?

**Comment by AJenbo** [comment]
The php refactor plugin simply Calles the tool via command line commands in the background

**Comment by zestllankesh** [comment]
Thanks again.


Cheers :)
