### ISSUE TITLE
Arrays in Local Report Not Working

### ISSUE THREAD

**Issue by metacogna** [eranif/codelite#1754]
It appears local variables in Codelite are not displaying properly and are compromised on a test machine by third parties.  This issue is either in CodeLite or GDB.   Is the current Codelite source known to be compromised or is it a GDB/related issue? 

It occurs on this code base on a possibly compromised machine that appears to be the target of a wide range of "specific intentional security abuse issues" of low-grade annoyance impact in an apparent solicitation for money which will be denied do to the means and methods used to solicit services.

3.2.0-4-amd64 ... deb http://repos.codelite.org/debian/ jessie contrib.

Please identify the source of the compromise and append their identity to this ticket if known.

**Comment by dghart** [comment]
>It appears local variables in Codelite are not displaying properly and are compromised on a test machine by third parties.

Please could you explain what you mean by this. Compromised in what way? What do you see? Is it only that machine? How can we try to reproduce the problem here?

> Is the current Codelite source known to be compromised?

CodeLite is open-source. You can see all its source-code yourself. Of course it has no known compromises, otherwise they would already have been fixed!

>This issue is either in CodeLite or GDB.

What happens if you run test program in gdb but _outside_ CodeLite? If you see the same thing, that suggests the problem is with gdb (unlikely for the same reasons) or with your test-code (a buffer overrun causing the display of random memory perhaps) or with that machine in general (do other programs show a similar behaviour there? Can you reproduce the problem on a different machine?)

**Comment by metacogna** [comment]
Thank you for the response. This is a complex issue under investigation. High level machine or kernel compromise is likely but the development environment needs to detect this. Please keep it open until resolved, we are working on it and will respond with more information. If the answer becomes clear, please post it.

**Comment by AJenbo** [comment]
Please add a description of what has cause you to suspect that there is an issue. Currently you have given us to little information to be able to reproduce the issue (what tools are you using to detect it, error messages etc, name or characteristics of the malware). It sounds more like your client has an already compromised machine that simply happens to have CodeLite installed.

If you need more time to investigate you can simply create a new issues once you have confirmed that there actually is an issue.
