### ISSUE TITLE
download codelite in linux 12.04 (64bits)

### ISSUE THREAD

**Issue by Rafoula** [eranif/codelite#1775]
Hello,
I have linux 12.04. How I can to download and install codelite 5.2 or newer version in my linux?

thanks!

**Comment by AJenbo** [comment]
I highly recommend you upgrade your system. Ubuntu 12.04 LTS reached its regular End of Life on April 28, 2017. No more package updates, including security updates, will be accepted to the 12.04 primary archive.

The latest version of Codelite is 10.0.7 and is only supported for Ubuntu 14.04 or later.

That being said it might be possible to install 9.1 using the repository :
http://codelite.org/LiteEditor/Repositories#toc1

Also please use the forum at codelite.org for support instead of Github issues (ment for issues with the code).
