### ISSUE TITLE
[Improvement] Keep tab/buffer status/positioning/scroll when switching between files

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1793]
When on buffer A and clicking on "go to definition" on some function call, it opens another buffer B. But after that, when going back to buffer A (using "Ctrl-<"), the cursor is on different position on the screen (although the line is right). 

For example, the active (current) line was on the bottom of the screen, but after the switches it can suddenly appear on the top of the screen.

Please keep the scroll position of every buffer

**Comment by Johndeep** [comment]
I agree on that, maybe a similar topic (but more of an issue) is also that after closing and opening codelite, the scroll position of some the previously opened files are not correctly restored, it seems that it tries to restore the position based on the cursor position from before and it sometimes fails to restore this position correctly, which results in the viewing part of the tab being far away from the previous viewing position (often far below, strangely).

It would be better to store the displayed codelines rather than the cursor position for restoring.
