### ISSUE TITLE
Control click over a symbol should jump to its definition

### ISSUE THREAD

**Issue by cirosantilli** [eranif/codelite#1811]
0a7342a9fef7aaeb27adb8b96b4b7142d9be9ab9

Like most IDEs.

Can do it with right click > Goto definition

**Comment by mysticall** [comment]
I use Codelite to read a part of FreeBSD [kernel](https://github.com/freebsd/freebsd/tree/master/sys) code. With Codelite version 9 in Linux and FreeBSD everything works well. But after version 9 "Find any Symbol" functionality does not works for me.
I installed Codelite version 10.0 and 11.0.1 on Debian Stretch. It creates about 500MB of refactoring.db file. But all the variables are with white color and nothing happens when I press Alt +Ctrl + Left Mouse button.
On Windows 10 with version 10.0 and 11.0.1 ... I can not even open the files.

**Comment by cirosantilli** [comment]
@mysticall I wonder when we will get an open source cross platform C / C++ IDE written in C++ and with libllvm backend that just works out of the box. The other option I found was kdevelop, but it too did not work out of the box :-( Back to ctags + cscope for now :-)

**Comment by eranif** [comment]
@cirosantilli in CodeLite you do this with `Alt-Ctrl-Click`
`Ctrl-Click` is used to create multiple carets. Hold `Ctrl` and keep clicking in the editor, you can then edit in multiple places at the same time

**Comment by cirosantilli** [comment]
Hmmm, that still didn't work, maybe it is conflicting with some ubuntu keyboard shortcut.

**Comment by eranif** [comment]
You can change it from settings->preferences->Tweaks->Code navigation key

**Comment by AJenbo** [comment]
I can confirm that it works on Ubuntu 16.04, although I have changed the Ubuntu shortcuts a little bit.

**Comment by eranif** [comment]
@mysticall FYI: I am currently refactoring multiple parts of CodeLite to support a better user experience when working with huge workspaces. Stay tuned

**Comment by mysticall** [comment]
Thank you for quick response. I am ready to test changes.

**Comment by eranif** [comment]
The workspace must be on the same drive as the sources. You can't have it any other way.
There is a good reason for this: everything is kept relative to the workspace.
With this design, the entire workspace folder can be copied to another drive - which make it possible to share it across different machines.

**Comment by AJenbo** [comment]
You could maybe achieve it using a sym-link
