### ISSUE TITLE
Crashed on a simplest programm. C++

### ISSUE THREAD

**Issue by pasha-pivo** [eranif/codelite#1934]
Hey guys!
I've just installed codlite 12.0-1unofficial.xenial. It has crashed on a very simple programm. Here it is:
```c++
#include <iostream>
using namespace std;

int main(int argc, char **argv)
{
    int *arr = new int[10];
	cout << "Hello world" << endl;
	return 0;
}
```
Then I went to the tab "memtest" and hit the green check. IDE has then crashed. Next time it worked.
Maybe there are any log files that I could attach?

**Comment by AJenbo** [comment]
~/.codelite/codelite.log there might also be one or two crash logs in the same folder

**Comment by pasha-pivo** [comment]
[codelite.log](https://github.com/eranif/codelite/files/1796362/codelite.log)
[codelite-stdout-stderr.log](https://github.com/eranif/codelite/files/1796363/codelite-stdout-stderr.log)
[crash.log](https://github.com/eranif/codelite/files/1796364/crash.log)

**Comment by dghart** [comment]
crash.log shows there was a C++ exception thrown, probably coming from libpthread or one of the wxWidgets libs (CodeLite uses the wxWidgets toolkit).

I just tested your program in my xenial x86_64 virtualbox guest, the one I used to build the package. It worked without crashing. 
It's hard to know why the difference. One possibility is that  xenial might have updated e.g. the libpthread package and we have different versions, but it isn't supposed to do so in a way that causes crashes.

I can't think of a way to solve the problem, but some possible workarounds:
You could build your own CodeLite, either directly from source or by using apt-source. 
Or you could wait for the next 'weekly' build to be released, as they are created on a different machine.
Otherwise, revert to CodeLite 11 for the next few weeks, then update to ubuntu 18.04 ;)

**Comment by pasha-pivo** [comment]
Thank you for your response. It's not a problem at all. This happened only once, at first start of the IDE. Next several runs went correctly.
I just thought that if it happened just away, on a "fresh" IDE (I upgraded it from... I don't remember the version), the report could be helpful. I sent it just in case. 
Cheers! =)
