### ISSUE TITLE
[CodeLite 12] Incorrect spacing and full-text hinting broken for certain fonts

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1958]
Fresh Fedora 27 installation with all updates installed and CodeLite 12. I've installed "Consolas" font, copying it from an existing Windows installation. In "Gnome Tweaks", I select "Full" text hinting for fonts.
When using Consolas at size 13, other applications, e.g. Geany seem to work fine, but CodeLite seems to have incorrect spacing, making the editor unusable.
![screenshot from 2018-03-22 13-09-21](https://user-images.githubusercontent.com/14065837/37792926-c7dcc8f8-2dd2-11e8-8181-ce5fb58ebdff.png)
Whitespace can be seen as dots - notice unusual blank spaces between them sometimes, also between letters and parenthesis, where it shouldn't be. Also, take a look at very first line (comment), where some dots are even inside the text.

The spacing actually changes on-the-fly, when you try to select something, looking quite weird:
![screenshot from 2018-03-22 13-13-27](https://user-images.githubusercontent.com/14065837/37792949-dfa39a66-2dd2-11e8-9cad-d54016e67145.png)

For comparison, here's screenshot for Geany:
![screenshot from 2018-03-22 13-14-41](https://user-images.githubusercontent.com/14065837/37792994-05ffb596-2dd3-11e8-8efe-b0e4d6e67051.png)

If I change text hinting to "Slight", or make font size smaller, the issue disappears. I've tried CodeLite 11, it doesn't seem to exhibit this issue, but it seems not to be using Full text hinting. 

Since I can only use Consolas at size 13 to match my Windows / Visual Studio configuration, this prevents me from using CodeLite at all. Is there any workaround for this? If I can help somehow to solve this issue, would be glad to do so.

**Comment by yunkot** [comment]
FYI, I've checked Code::Blocks 17, which as far as I know uses the same Scintilla-based editor as CodeLite, doesn't exhibit the issue either, so CodeLite seems to be the only one affected by this.

**Comment by dghart** [comment]
Hi,

CodeLite, like Code::Blocks, is using the wxWidgets class wxStyledTextCtrl for its editors. wxStyledTextCtrl is a wrapper for Scintilla. 
CodeLite 12.0 is built against wx3.1.1 which upgraded to Scintilla 3.7.2. I strongly suspect that the problem is due to that version of Scintilla; presumably Code::Blocks uses a different one. IIRC CodeLite 11 was built against wx3.1.0 (you can check by doing ctrl-alt-middleclick on it; the dialog will say which wxWidgets version it uses) which had Scintilla 3.5.5.

You could check if I'm right by installing the Scite version that uses 3.7.2. Or you could build CodeLite 12.0 against wx3.1.0 (available from http://codelite.org/LiteEditor/WxWidgets310Binaries#toc3).

Regards,

David

**Comment by eranif** [comment]
In any case, I don't think we can fix this, as we dont work directly with the OS internals, but rather we interface with wxWidgets. You will have to take it with them and report it as bug to the wxWidgets project
