### ISSUE TITLE
Does not open whatsoever on macOS High Sierra 10.13.3

### ISSUE THREAD

**Issue by johnnyschneider** [eranif/codelite#1962]
Running on an iMac 2012.1 - MacOS Extended (Journaled, Case Sensitive, Encrypted). After unpacking with the archive tool it just does not run. MacOS places a symbol on it (before I even open it) that indicates that the app is damaged or incompatible in some way.

**Comment by AJenbo** [comment]
Did you allow non signed application in your security center?

**Comment by johnnyboy21** [comment]
Yes! I don't have the time right now, but I want to see if it has anything to do with case-sensitivity. I'll boot from an old clone and install 12.0 on that, and see what happpens... I recently updated my OS and the FS along with it. This is not my first time encountering apps that fail because of case-sensitivity incompatibilities on macOS. 

I know that in the realm of bugs it's unlikely to be that but Adobe software in general has issues, even old apps coming from the Leopard/Lion days had issues with the case-insensitivity at first. I think it's worth looking at it. Although, I don't know anything about whether the developers can 100% confirm case sensitivity compatibility, and if they can I don't want to discredit them.
