### ISSUE TITLE
Crashes randomly on save (macOS)

### ISSUE THREAD

**Issue by jockm** [eranif/codelite#1991]
Code::Lite crashs when saving files the behavior is inconsistent.  It happens most often when I create a new file and hit Cmd+S out of habit, but it can happen any time I save.  I also seems to happen (again inconsistently) when a file is autosaved when a build is triggered.

While it can happen at any time, it *seems* to happen most shortly after launch.  If I can make it past 2-3 minutes I am normally OK for the next 45+ minutes.

This happens several times a session when using macOS, but I have not yet observed it on my windows system

Running 12.0.0 on macOS 10.13.4.

**Comment by jockm** [comment]
Upon further experimentation it appears that the autosave plugin may be to blame.  I disabled it and have not observed a crash since.

**Comment by sergeysanders** [comment]
Same here, but crashes without autosave plugin and doesn't crash on compile-autosave.
 
>
 Process:               CodeLite [12495]
Path:                  /Applications/codelite.app/Contents/MacOS/CodeLite
Identifier:            com.eranif.CodeLite
Version:               CodeLite IDE version 12.0.0 (CodeLite IDE version 12.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CodeLite [12495]
User ID:               1000

Date/Time:             2018-05-15 10:34:17.693 -0300
OS Version:            Mac OS X 10.13.4 (17E202)
Report Version:        12
Anonymous UUID:        55979722-2A7D-37B0-2660-F95B286705C5

Sleep/Wake UUID:       15E292E4-D3AD-4D16-84EE-016852C4A1D8

Time Awake Since Boot: 53000 seconds
Time Since Wake:       6500 seconds

System Integrity Protection: enabled

Crashed Thread:        2

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x6080004aa2c0: pointer being freed was not allocated
 

Thread 0:: Dispatch queue: com.apple.main-thread
0   com.apple.AppKit              	0x00007fff460d57fe -[NSAppearanceAuxiliary allowsVibrancy] + 0
1   com.apple.AppKit              	0x00007fff46234a11 -[NSView viewWillDraw] + 67
2   com.apple.AppKit              	0x00007fff469ab6cf _NSViewWillDraw + 45
3   com.apple.AppKit              	0x00007fff462346b9 -[NSView _sendViewWillDrawInRect:clipRootView:] + 1640
4   com.apple.AppKit              	0x00007fff46232efd -[NSView displayIfNeeded] + 1142
5   com.apple.AppKit              	0x00007fff46232a52 -[NSWindow displayIfNeeded] + 321
6   com.apple.AppKit              	0x00007fff469d360d ___NSWindowGetDisplayCycleObserver_block_invoke.5902 + 308
7   com.apple.AppKit              	0x00007fff4623255e __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 695
8   com.apple.QuartzCore          	0x00007fff53e873c3 CA::Transaction::run_commit_handlers(CATransactionPhase) + 49
9   com.apple.QuartzCore          	0x00007fff53e85ea5 CA::Transaction::commit() + 171
10  com.apple.AppKit              	0x00007fff469eaa72 __65+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke + 283
11  com.apple.CoreFoundation      	0x00007fff48b76467 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
12  com.apple.CoreFoundation      	0x00007fff48b7638f __CFRunLoopDoObservers + 527
13  com.apple.CoreFoundation      	0x00007fff48b58908 __CFRunLoopRun + 1240
14  com.apple.CoreFoundation      	0x00007fff48b581a3 CFRunLoopRunSpecific + 483
15  com.apple.HIToolbox           	0x00007fff47e40d96 RunCurrentEventLoopInMode + 286
16  com.apple.HIToolbox           	0x00007fff47e40a0f ReceiveNextEventCommon + 366
17  com.apple.HIToolbox           	0x00007fff47e40884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
18  com.apple.AppKit              	0x00007fff460f3a73 _DPSNextEvent + 2085
19  com.apple.AppKit              	0x00007fff46889e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
20  com.apple.AppKit              	0x00007fff460e8885 -[NSApplication run] + 764
21  libwx_osx_cocoau-3.1.dylib    	0x000000010bd77804 wxGUIEventLoop::OSXDoRun() + 116
22  libwx_osx_cocoau-3.1.dylib    	0x000000010bc8f294 wxCFEventLoop::DoRun() + 52
23  libwx_osx_cocoau-3.1.dylib    	0x000000010bbf5de8 wxEventLoopBase::Run() + 88
24  libwx_osx_cocoau-3.1.dylib    	0x000000010bbc7590 wxAppConsoleBase::MainLoop() + 128
25  libwx_osx_cocoau-3.1.dylib    	0x000000010bd1907a wxApp::OnRun() + 26
26  libwx_osx_cocoau-3.1.dylib    	0x000000010bc2553e wxEntry(int&, wchar_t**) + 62
27  com.eranif.CodeLite           	0x000000010b490cc4 main + 20
28  libdyld.dylib                 	0x00007fff70e6e015 start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff70fb520a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff70fb4724 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff48b597d5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff48b58b27 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff48b581a3 CFRunLoopRunSpecific + 483
5   com.apple.AppKit              	0x00007fff46230fc4 _NSEventThread + 184
6   libsystem_pthread.dylib       	0x00007fff71186661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff7118650d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff71185bf9 thread_start + 13

Thread 2 Crashed:
0   libsystem_kernel.dylib        	0x00007fff70fbeb6e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff71189080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff70f1a1ae abort + 127
3   libsystem_malloc.dylib        	0x00007fff71018822 free + 521
4   liblibcodelite.dylib          	0x000000010f1aea05 TagsOptionsData::DoUpdateTokensWxMap() + 117
5   liblibcodelite.dylib          	0x000000010f1af477 TagsOptionsData::ToString() + 375
6   liblibcodelite.dylib          	0x000000010f0cb89d TagsManager::SourceToTags(wxFileName const&, wxString&) + 941
7   liblibcodelite.dylib          	0x000000010f0a0f76 SourceToTagsThread::Entry() + 166
8   libwx_osx_cocoau-3.1.dylib    	0x000000010bc9c6cf wxThread::CallEntry() + 15
9   libwx_osx_cocoau-3.1.dylib    	0x000000010bc9c5a7 wxThreadInternal::PthreadStart(wxThread*) + 1351
10  libsystem_pthread.dylib       	0x00007fff71186661 _pthread_body + 340
11  libsystem_pthread.dylib       	0x00007fff7118650d _pthread_start + 377
12  libsystem_pthread.dylib       	0x00007fff71185bf9 thread_start + 13

>
