### ISSUE TITLE
How to input emoji characters

### ISSUE THREAD

**Issue by zenera** [eranif/codelite#2015]
Ubuntu 18.04 supports colour emoji characters.
Gedit and Gnome Terminal supports copy & paste of emoji characters.

Codelite editor lacks supporting recent Unicode characters.

**Comment by eranif** [comment]
This is part of the wxWidgets toolkit. Nothing that can be done from CodeLite's side

**Comment by ialokim** [comment]
This might be related or not, but I've been experiencing some strange behavior using emojis in source code with CodeLite: If I copy e.g. [this smiley](https://emojipedia.org/grinning-face/) (😀) into the editor, it shows me the following:
![grafik](https://user-images.githubusercontent.com/18088991/93883981-96bd0580-fce2-11ea-9aec-e2b032ee460c.png)

Same happens if the loaded file already contains an emoji and while saving the file to disk, it converts the emoji to some very strange characters (`'í¼í½§,` in this example, as read by Geany).

I don't think this is really a problem of wxWidgets (anymore?), as e.g. in the search field it can indeed show me the emoji as expected:
![grafik](https://user-images.githubusercontent.com/18088991/93884713-8b1e0e80-fce3-11ea-8d09-273f49739d0a.png)
