### ISSUE TITLE
WxWidgets 3.0.x vs 3.1.x

### ISSUE THREAD

**Issue by kekePower** [eranif/codelite#2093]
Hi.

Please consider the usage of functions from WxWidgets 3.1.x since this is a development branch and I think that quite a few distros are conservative when they distribute packages.
In my case, Mageia will not distribute a development package unless it will become a stable package before the next major distro release and hence we're still using Wx 3.0.4.

I understand the need for and your desire to develop your application.

Cheers,
kekePower

**Comment by eranif** [comment]
Because of this, we usually provide a pre-compiled binaries for wxWidgets (checkout our wiki page for more details)
I assume that you are facing an issue when building CodeLite by yourself, however, building wxWidgets is very easy on Linux (much easier than building CodeLite)
http://codelite.org/Developers/Linux

wx3.0.4 lacks some basic wxStyledTextCtrl features which are only available in wx3.1.X this is why we moved to wx3.1 and this can not be reverted
