### ISSUE TITLE
Editing text using quotation marks "" in project configuration appears to create unknown multibyte characters and breaks build commands.

### ISSUE THREAD

**Issue by Smeerak** [eranif/codelite#2179]
Paste the following into the linker options: (note this appears to be present in all text edit boxes for paths/options)

"testing 1 2 3"

It appears the quotation marks break the text editor. If click 'ok' and then edit again, the problem is worse. Based on deleting, it appears the new characters are multibyte.

Here is the original text that I was pasting which discovered the issue. I have also attached some screen shots to show the results using the above text.

-nostdlib -Xlinker -Map="empty.map" -Xlinker --gc-sections -Xlinker -print-memory-usage -Xlinker --sort-section=alignment -mcpu=cortex-m0plus -mthumb -T empty_Debug.ld -o "empty.axf"

<img width="501" alt="codelite_bug_after_paste" src="https://user-images.githubusercontent.com/10552925/48881935-488d0180-edee-11e8-860c-f30461bc450f.png">
<img width="502" alt="codelite_bug_after_edit" src="https://user-images.githubusercontent.com/10552925/48881938-4cb91f00-edee-11e8-8c0c-52476ec6fe78.png">

**Comment by eranif** [comment]
This is because you didn't copy a double quoted text, but rather you used something similar to MS Word double quotes (which is NOT double quotations marks). These are also known as "Straight Quotes"

https://typographyforlawyers.com/straight-and-curly-quotes.html
Delete those quotes and insert them by hand and it will work
