### ISSUE TITLE
Editor split siew

### ISSUE THREAD

**Issue by testalucida** [eranif/codelite#2223]
I just installed version 12.0.11. Couldn't find how to split editor's view.
I'm aware of issue #1179 closed by eranif pretending issue was solved. What am I doing wrong?
Thanks.

**Comment by eranif** [comment]
You are not doing anything wrong.
This issue was closed due to some un-solved issues with the current Notebook (which can not be fixed without replacing the entire notebook control of CodeLite)
I closed it because I simply don't have time to fix it and no one else seems to took the time and fix this :)
As always, patches and pull requests are most welcomed and I usually apply them in matter of days

Thanks

**Comment by wonbinbk** [comment]
What a pity to not have split view in CodeLite!!! :(
I love to use CodeLite and view splitting is, like, the only feature that I miss. Currently I open another Kate window to view a file side by side.
I know @eranif  doesn't have time to fix this issue and sadly my level of C++ coding is so noob I couldn't help.
