### ISSUE TITLE
Add Language Server Protocol

### ISSUE THREAD

**Issue by Lyberta** [eranif/codelite#2232]
[Language Server Protocol](https://langserver.org/) is a standard for implementing smart features such as code completion in IDEs. It's a good thing that now we don't have to reinvent the wheel and use existing language servers. I think adding this feature to CodeLite is crucial in order to get sensible auto complete and other features because current ones almost never work, at least in C++.

**Comment by eranif** [comment]
Thanks. This is a good idea. I have already started implementing the network protocol for later integration with `clangd` daemon.

ALSO, you should know that CodeLite already supports `clang` code completion. You can enable it from `Settings->Preferences->Code Completion->Enable clang code completion`

**Comment by eranif** [comment]
Implemented. Tested with clangd-7 on Windows & Linux. The plugin `Language Server` is generic and can accept any LSP server

**Comment by eranif** [comment]
It will be great if you could test it locally. I can provide you a binary if needed

Thanks

**Comment by mtangoo** [comment]
I have latest CodeLite here. I can test it. How do I enable it?

**Comment by eranif** [comment]
@mtangoo  you will need the latest trunk.
* Which OS are you using?
* What build system do you use (CMake, CodeLite's Makefile generator etc)

**Comment by mtangoo** [comment]
>Which OS are you using?
MacOs High Sierra

>What build system do you use (CMake, CodeLite's Makefile generator etc)

CMake

**Comment by eranif** [comment]
If you will fetch today's sources, you should get a working LSP on macOS. How to configure it? I should write a small installation guide first :)

**Comment by mtangoo** [comment]
Should I wait for that guide? I thought it should "just work" in place of Clang since I see a lot of Clang stuffs deleted

**Comment by eranif** [comment]
Language Server is for *all* languages.
You need to install the language server per the language you want. You can find a complete list of all available servers on the [Language Server Web SIte](https://langserver.org)

The installation is quite straight forward, but I will still right a guide.

**Comment by eranif** [comment]
BTW, Apple too did move to the language server for their XCode product. The LLVM team (the people behind clang) are encouraging people to use the `clangd` (the language server for C/C++Object-C{++})
So there is no need to link against `clang` directly. Instead, I am now using the common protocol LSP to communicate with `clangd`

**Comment by mtangoo** [comment]
>The installation is quite straight forward, but I will still right a guide.
That one will be easy for me. As I was reading LSP it leaves open as to means of communication. I hope all of them uses TCP IP/HTTP

**Comment by mtangoo** [comment]
>BTW, Apple too did move to the language server for their XCode product. 
Everyone is moving towards there.. even us here :)

**Comment by mtangoo** [comment]
It is hard to maintain multiple languages Intellisense. I agree with you moving CL that direction. Focus should be on making IDE better instead of Intellisense

**Comment by Lyberta** [comment]
Does this mean integrated CTags and clang autocompletion can be removed now? I think LSP is where all the effort is focused now.

**Comment by mtangoo** [comment]
>Does this mean integrated CTags and clang autocompletion

@eranif will give definitive answer but what I can deduct from history is:
1. Ctags was old efforts to achieve something LSP is archieving and surpassing
2. Clang will be integrated but now via Apple drummed Clang daemon

**Comment by eranif** [comment]
@Lyberta I don't think I will remove the ctags completion (its not really ctags completion, its a modified version of ctags that supports templates). In any case, ctags can't really provide auto-complete, it can only generate a lookup table. The rest of the completion is done via an in house parser I have written using yacc/flex 10 years ago :P 

However, since there is only one real LSP server for C++  and it is based on clang, (`clangd` to be more precise), I don't think it can really replace the current one. As clang needs to compile the source, it is relatively slow compared to the current code completion and it is less "forgiving" (i.e. if it can't find an include file, it will not provide auto completion for the file). For large projects (like CodeLite itself), I don't think its enough nor it can handle it. However, for smaller code bases (hundreds of files) it's more than enough. Another downside is that clangd precompiles every source file CodeLite passes to it, and generates a .pch file (pre-compiled header which holds the AST). This means that for code base like CodeLite, it will easily consume 10 or more GB of storage for these files

**Comment by mtangoo** [comment]
>This means that for code base like CodeLite, it will easily consume 10 or more GB of storage for these files.

This is outrageous!
