### ISSUE TITLE
Regression for Preferences, Colours and Fonts dialogs

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#2253]
CodeLite 12.0.15 (Weekly Build April 1, 2019) Windows x64 on Win10 1809.

These two dialogs not resize properly.
The height exceeds screen height on 1366x768 display and can't resized down.
Only resizable on horizontal direction, but can only resize down to about 3/4 screen width.

Hope this is not a April joke.

**Comment by eranif** [comment]
This should be a lesson for you: dont install April fool day release :)
Now, seriously, indeed its a regression I will fix this asap

**Comment by zufuliu** [comment]
By the way, a new bookmark symbol is added in Scintilla.
https://sourceforge.net/p/scintilla/feature-requests/1276/

**Comment by morgoth6** [comment]
I think I was hit by same or similar problem. Both mentioned windows opened correctly first time, but second atempt result in window with has extremaly huge height (but still working normaly) and any ne atempt result in empty window with many errors reported as:

```
Gtk-CRITICAL **: 16:25:13.500: gtk_window_resize: assertion 'width > 0' failed
...
Gtk-WARNING **: 16:27:51.043: infinite surface size not supported
...
Gdk-WARNING **: 16:25:13.523: Native Windows wider or taller than 32767 pixels are not supported
...
Gtk-CRITICAL **: 16:25:13.597: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
```

The ugly thing was after that I was unable to open the windows normally (result was empty window) after restarting CL. In order to restore was to remove persistency.ini file. The contents after this problem occurs looks interesting I guess:

```
[Persistent_Options/Window/SyntaxHighlightDlg]
x=460
y=152
w=36511
h=-2023029984
Maximized=0
Iconized=0
decor_l=32671
decor_r=0
decor_t=0
decor_b=-2023093494
```
To be clear I use single HD monitor with regular 1920x1080 resolution ;)
