### ISSUE TITLE
bug: items in explorer tree have extra padding

### ISSUE THREAD

**Issue by pimlie** [eranif/codelite#2256]
After I misclicked the right mouse button yesterday (but not sure if its related) suddenly all items in the explorer tree have an extra top and bottom padding:
![image](https://user-images.githubusercontent.com/1067403/55942551-ef125b80-5c44-11e9-8083-4603b58f4da6.png)

I already removed my `~/.codelite` folder, added a folder back to the explorer tree and that folder was displayed 'normally'. But when I expanded the tree for that folder it again uses the double padding. Is there some more configuration hiding somewhere?

I am using stable Codelite v12.0.0 on Ubuntu 18.04

-- update --

It seems this was caused by a (mistakenly) written file in one of my project folders (and the misclick was just a refresh of the tree apparently). The file had the exact name ` ### Fix'$'\n\n''- fix: fixed it for ya` (dont ask me why, as said it was wrongly written during testing :blush: ), after removing that file the tree doesnt use a double padding anymore

**Comment by eranif** [comment]
This is a 4k / HiDPI issue. The problem is that some images (has "normal" size image size that can be displayed properly in 4k / hidpi displays. The file that you removed probably caused CodeLite load an unknown image to the tree, that image did not support 4k/hidpi scaling, so the image loaded by the tree (`wxTreeCtrl`) was too big (in size) which caused the whole tree to add extra padding (the rows in the trees are using the maximum row height that found, which in your case was the file that was loaded into the tree. Why does it happen only when you expanded the folder? this is simply because the tree evaluates as you expand it. i.e. when a folder is in a "collapsed" state and you (the user) never expanded it before, its actually empty with a single entry named "dummy" (so the tree will display the "expand/collaose" button), once you expand it for the first time, CodeLite accesses the file system to fetch the file list and populate the folder with the found entries.

Hope I was clear :)

Anyways, CodeLite no longer uses `wxTreeCtrl` (I wrote my own control, `clTreeCtrl` which fixes this issue among others)

I highly recommend that you install CodeLite 12.0.14 from our site.
https://forums.codelite.org/viewtopic.php?f=20&t=4190

Eran

**Comment by pimlie** [comment]
You were more than clear, thanks for taking the time to explain it!

Actually I had auto-update enabled, not sure why it didnt update automatically. Or maybe its because 12.0.14/5 is considered an unstable release? Anyway, just upgraded and I like the new looks!

Btw, I have said it before but still wanted you to know I love your work on Codelite. Nothing beats a native program in terms of responsiveness. I guess I just dont like the soft-touch, almost sluggy, feel of other popular editors. Codelite always feels sharp and crisp if you know what I mean ;)
(and if only I were better at C++, I would have contributed eg a plugin already for sure)
