### ISSUE TITLE
[Feature Request] Language Server Template

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#2260]
I think it's better to bundle some language server templates with CodeLite installer.
When adding new language server, based on selected executable and languages (e.g. when clangd is selected as the executable), other fields on the dialog will auto filled.

I think clangd can be auto added as a language server when clang is detected.

**Comment by eranif** [comment]
I could implement `auto-detect` feature for commonly used language servers (clangd, php and js)
If you are using the new language server (namely clangd), I would love to hear feedback

Thanks

**Comment by zufuliu** [comment]
How do I know clangd works? here is my configuration (with GCC 8.3.0 from MYSY2 and LLVM 9.0 SVN r358402 from https://llvm.org/builds/):
![clangd](https://user-images.githubusercontent.com/2289926/56463853-1e785380-640f-11e9-8d00-43d15f1bbfb5.png)

but I see clang-tool is executed, which doesn't exists.
```
D:\Dev\LLVM\bin\clang-tool -ID:\Dev\gcc\include\c++\8.3.0 -ID:\Dev\gcc\include\c++\8.3.0\x86_64-w64-mingw32 -ID:\Dev\gcc\include\c++\8.3.0\backward -ID:\Dev\gcc\lib\gcc\x86_64-w64-mingw32\8.3.0\include -ID:\Dev\gcc\include -ID:\Dev\gcc\lib\gcc\x86_64-w64-mingw32\8.3.0\include-fixed -ID:\Dev\gcc\x86_64-w64-mingw32\include -ID:\notepad2\np2\src -ID:\notepad2\np2\scintilla\include -ID:\notepad2\np2\scintilla\lexlib -ID:\notepad2\np2\scintilla\src -DWINVER=0x0502 -DUNICODE -DNO_CXX11_REGEX -D_UNICODE -DSCI_LEXER -DNDEBUG -D_WIN32_WINNT=0x0502 -D_WIN64 -target x86_64-pc-windows-gnu D:\notepad2\np2\scintilla\src\AutoComplete.cxx -fsyntax-only -resource-dir=D:\Dev\LLVM\lib\clang\9.0.0
```

By the way, change `D:\notepad2\np2\build\CodeLite` to `$(WorkspacePath)` not working:
```
[08:36:10:593 DBG] [Main] Path specified by --compile-commands-dir does not exist. The argument will be ignored.
I[08:36:10.658] Failed to find compilation database for D:\notepad2\np2\scintilla\src\AutoComplete.cxx
```
these variables in makefile:
```makefile
ProjectName            :=Notepad2
ConfigurationName      :=Release_x64
WorkspacePath          :=D:/notepad2/np2/build/CodeLite
ProjectPath            :=D:/notepad2/np2/build/CodeLite
IntermediateDirectory  :=$(WorkspacePath)/../bin/$(ConfigurationName)/obj/$(ProjectName)
OutDir                 := $(IntermediateDirectory)
```

**Comment by eranif** [comment]
If you are building using CodeLite default build system (i.e. no CMake, just the plain old generated Makefiles by CodeLite), then you shouldn't pass anything to `clangd` - CodeLite will generate `compile_commands.json` for you at the end of each build. So clear the `arguments` field. You should know that `clangd` does not work on Windows + MSYS without some modifications. You must use the `compile_commands.json` file that CodeLite generates and not the one you created it won't work from several reasons:

1. `clangd` does not know where to find the system headers (e.g `<string>`)
2. `clangd` needs special flag to be passed per compile line: `-target "x86_64-pc-windows-gnu` - otherwise it will default to VS, which fails to work with MSYS

This is why you must not pass your own `compile_commands.json` file

How to check if it actually works?
If you don't have the flags mentioned in point 2 or you did not add the paths to the global system headers (its multiple paths) - it wont work.

So, to summarise:

1. Remove the `Arguments` field
2. Increase the `clangd` priority to 90 (with the default 50, the builtin code completion has a priority, which means it will work before `clangd`). Setting it to 90, will give it the priority and it will work exclusively (with 50 the builtin code completion works, if it fails, the completion request is passed to `clangd`). You can read more about it here: https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

You can always enable the logging from `Settings->Preferences->Log->Log Verbosity->Debug`
and check the output in `%appdata%\CodeLite\codelite.log`

`clangd` caveats: it does not auto reload `compile_commands.json` files, i.e. if you add a new class or files into your project a new `compile_commands.json` needs to be generated. However, `clangd` will not reload it, unless restarted. CodeLite solves this by keeping checksums on the active `compile_commands.json` and restarts `clangd` if a new `compile_commands.json` was found

Tested on Windows + MinGW. `clangd` versions tested: 8 and 7. So please try to use one of the tested versions (I don't think version 9 was released yet... the current release is 8)

**Comment by eranif** [comment]
You should know that I have been using `clangd` (v8) on Windows for the last month now without any problems. My configuration is set so code completion is provided by `clangd` exclusively and it works pretty fast and without bugs (beside the ones that I know of, such as: `clangd` does not function well within header file)

**Comment by alex-rass-88** [comment]
If using cmake and out of source build, clangd cant find compile_commands.json.

May be expand project macro to plugins?
And default arguments for clangd "-compile-commands-dir=$(WorkspacePath)"

**Comment by eranif** [comment]
Nice idea, I will implement this. Stay tuned
