### ISSUE TITLE
wxcrafter generate wrong include sequence for aui manager

### ISSUE THREAD

**Issue by billcxx** [eranif/codelite#2298]
windows 10
wxWidget version 3.1.2
wxCrafter 2.9
codelite 13.0

Minimal aui setup.
![image](https://user-images.githubusercontent.com/3356113/60375317-b4fc5e80-99d6-11e9-9ab1-e5bb41bf3028.png)

The generated wxcrafter.h file has the following include lines
```
#ifndef _WXWIDGET_TEST_WXCRAFTER_BASE_CLASSES_H
#define _WXWIDGET_TEST_WXCRAFTER_BASE_CLASSES_H

#include <wx/artprov.h>
#include <wx/aui/dockart.h>
#include <wx/aui/framemanager.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/menu.h>
#include <wx/panel.h>
#include <wx/settings.h>
#include <wx/sizer.h>
#include <wx/toolbar.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/xrc/xmlres.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/treebook.h>
#endif
```
 
The problem is  ```#include <wx/aui/dockart.h>``` should come after ```#include <wx/aui/framemanager.h>```, otherwise error occurs
![image](https://user-images.githubusercontent.com/3356113/60375472-656a6280-99d7-11e9-9093-3ed51348fc95.png)

**Comment by eranif** [comment]
CodeLite does generate the correct order (see attached screenshot)
I believe the problem is that you are using `clang-format`, notice that one of its settings (I think it's enabled by default) is to remove duplicate includes and order them. I had this problem (not this one exactly, but similar) I had to update CodeLite's `.clang-format` https://github.com/eranif/codelite/blob/master/.clang-format see the last entry: `SortIncludes: false`

As a temporary solution you might want to add `.clang-format` to your project and set it with `SortIncludes: false` 

On my end, I will probably wrap the generated `#include` lines with
`// clang-format off` and `// clang-format on`

![aui](https://user-images.githubusercontent.com/3677711/60834607-b34a4c00-a1c9-11e9-8636-2a603aae2320.png)
