### ISSUE TITLE
Project structure not created

### ISSUE THREAD

**Issue by Nyrathalnian** [eranif/codelite#2324]
When creating a new project within a workspace the files are all added to the main workspace folder instead of creating its own folder structure.  This is preventing the project from being created correctly and currently Codelite is not usable due to this issue.

**Comment by blockchaindevel** [comment]
Agreed.
This is in the New Project Dialog for the 13.0.1 weekly build. 
- There should be a checkbox similar to the one in the previous version of CodeLite to 'Create the project under a separate directory'. Otherwise the user is forced to do this manually.
- Please make the 'Default' Build System the default that actually displays. Currently it is CMake.
- Finally, when selecting the project type we now get a drop down list that is just too large. I'm not sure this simplifies the New Project dialog at all. Can you default the choice to the previously chosen type so we don't have to wade through all the choices?

May I ask what prompted the redesign of the New Project dialog?

![NewProject](https://user-images.githubusercontent.com/52295768/63630267-dba9d080-c5e6-11e9-9265-f46df533fd3f.png)
Thanks for a great IDE!
bcd

**Comment by eranif** [comment]
@blockchaindevel 
1. You can type the path you want (even if it does not exist), CodeLite will create it. I will try and make this a bit simpler
2. The "Default" issue was already fixed in git master
3. I agree the list is too long and it can be fixed a little bit

**Comment by eranif** [comment]
@Nyrathalnian the issues mentioned by @blockchaindevel are not related to your issue.
If you want that the file system layout will match the one in the workspace, you will have to use the Import Files option (right click on the project)

**Comment by Nyrathalnian** [comment]
I had to downgrade to the older version because the new functionally is clunky.  Can this please be updated to have the same functionality that the current IDE does, versus making it harder to do something that everyone needs to do?

**Comment by eranif** [comment]
@Nyrathalnian  I am not sure what are you talking about... please elaborate

**Comment by Nyrathalnian** [comment]
See the message from blockedchainlevel, there is no way to create a project with it's own directory in the latest version.  It is putting all the files in the main directory without a proper finder structure.  There should be a way to do this like the current version, either by a checkbox or by default.

**Comment by eranif** [comment]
ofc there is, just type the name of the folder - and it will be created.
In 13.0.2 this was fixed and I re-introduced the checkbox

**Comment by eranif** [comment]
As this was already fixed in git master, I am closing this bug.
