### ISSUE TITLE
New Build System: support an automated upgrade from the deprecated one

### ISSUE THREAD

**Issue by blockchaindevel** [eranif/codelite#2327]
Hi,
I have a Workspace and Project created prior to CodeLite 13.0.1
The project was created using the Default Build System.

When I Clean and Build this project, CodeLite 13.0.2 is using the build-Debug directory rather than the original Debug directory.

However, when I run the Project, it is looking for the project in the original Debug directory.
In some cases the executable may be there and it will run an incorrect executable. 
In the case that the executable is not there, an error occurs.

The same issue is seen when in Release and Debug configs.

I tried changing the Build system to Classic (DEPRECATED) but the behavior seems to be the same.
Thanks

**Comment by eranif** [comment]
If you want the old behavior change the project  build type back to the deprecated version.
Otherwise, with the new build system, all objects are placed under a single directory:
`$(WorkspacePath)/build-$(WorkspaceConfiguration)`
The artifacts (executables, shared objects etc) are placed under:

- Executables: `$(WorkspacePath)/build-$(WorkspaceConfiguration)/bin`
- Shared objects and Static libraries `$(WorkspacePath)/build-$(WorkspaceConfiguration)/lib`

If the debugger / execute does not work for you, change the 'Executable to Debug / Run' from under `Project -> Settings -> General -> Executable to Run /Debug`

**Comment by eranif** [comment]
In order to help you out, you need to provide an *exact*  error message + steps to reproduce + working sample...

**Comment by eranif** [comment]
I am currently implementing an automated upgrade detection, it should fix the project settings to match the new builder file system layout once a project is loaded. Hopefully, this should fix your problem and eliminate the tedious work of doing this by hand

**Comment by eranif** [comment]
This https://github.com/eranif/codelite/commit/a27aa75fd8e90036bfae8fdc08469aea557c57ad implements this. It will be available in 13.0.3
