### ISSUE TITLE
codelite looks ugly on windows 7

### ISSUE THREAD

**Issue by Shadowblitz16** [eranif/codelite#2352]
codelite is looking very different from the screen shots i see online

![image](https://user-images.githubusercontent.com/2453707/66680503-8e7ccf00-ec25-11e9-883a-d5415eeeb572.png)

![image](https://user-images.githubusercontent.com/2453707/66680627-d3a10100-ec25-11e9-8580-a7f37cb0cb45.png)

is there a way to make it look more native on windows 7?

**Comment by eranif** [comment]
Indeed, these screenshots were taken back in CodeLite 5.0 :)
I did not have the time to update them since.

I will release today CodeLite 13.0.4 which includes some UI fixes. I am not sure how will it look on Windows 7. But you can change the default `GTK3` theme from `Settings ->Preferences -> Windows & Tabs -> Tab style`

The toolbar is hidden by default, but it's there. You can hit `Ctrl-F11` (once or to enable various UI elements which are hidden by default)

**Comment by eranif** [comment]
This is how it looks with the bright theme enabled:

![cl](https://user-images.githubusercontent.com/3677711/66771726-b0937d00-eec3-11e9-94d1-25016e13ff36.png)

and this is the dark theme:

![cl-dark](https://user-images.githubusercontent.com/3677711/66771812-e89ac000-eec3-11e9-8b54-0eeff19c8065.png)

**Comment by Shadowblitz16** [comment]
thankyou I will look into this. :D
