### ISSUE TITLE
Edited line highlight disappears when CodeLite is restarted.

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#2363]
Anytime I edit a line of code, I see a VERY helpful highlight indicator (just to the right of the line number).  However, if I close CodeLite and start it up again, these highlights no longer appear.

OS:   Debian 10.1
CodeLite version:  12.0  (installed via apt-get install)
Note: I also installed the associated CodeLite plugins the same way.

**Comment by eranif** [comment]
these lines (green when saved, red while editing, or orange) are markers that shows which files were modified since the file loaded into the editor. When you restart CodeLite, these changes are gone cause the file loaded into CodeLite, compared the  version on the disk, is identical. They will also be gone if you do a `File->Reload file` . This is by design.. If you wish to track changes across long period of time, you should use (if you are not already using..) a source control tool, e.g. `git`

**Comment by green-eyed-bear** [comment]
Should the "changed lines indicator" persist a CodeLite restart when using the "git plugin"?  That was my expectation, and probably should have mentioned I was using it.
