### ISSUE TITLE
Copy and Paste Not Working Properly

### ISSUE THREAD

**Issue by Zakkumaru** [eranif/codelite#2402]
Using the latest Manjaro Gnome and CodeLite build via AUR.

Copy and paste is erratic, mostly never copying correctly.  Copying things from outside the IDE will paste into the IDE with 100% success.  Copying something within the IDE will only work about 50% of the time.  When it does copy, if it's a lot of text at once, it will only copy about 70% of the text.

Using the getter/setter generation and the Implement All Unimplemented Functions feature will not work if there are more than half a dozen things to generate.  If the .cpp file is too big, it will generate a bunch of foreign characters on a single line, erasing about half the file in the process, instead.

It's been suggested that I use a different clipboard manager.  This doesn't do any good, and the CodeLite IDE is the only thing I have trouble with copying and pasting.

It has also been suggested that I increase buffer size, but this seems to be unrelated to the issue at hand.

The third suggestion I was given is to not use Gnome.  I'm down for this option, but it would actually make like easier if I could get around this and get the issue fixed, instead.

**Comment by eranif** [comment]
Tbh, the clipboard is completely managed by wxWidgets. 
So what I would do here is:

- Which version of CodeLite are you using?
- Which version of wxWidgets?
- Which version of GTK?

I would try and build CodeLite from sources instead of using AUR - this will make sure you are using the latest. In addition, I would build wxWidgets against different version of GTK (i.e. if you are using GTK3, use GTK2 and vice versa)

**Comment by Fushko** [comment]
> Tbh, the clipboard is completely managed by wxWidgets.
> So what I would do here is:
> 
>     * Which version of CodeLite are you using?
> 
>     * Which version of wxWidgets?
> 
>     * Which version of GTK?

Same issue here.
- CodeLite 14.0.0 
- wxWidgets 3.0.4
- GTK 3.24.13 and 2.24.32 (both installed)
- Gnome 3.34.2
- Pop OS 19.10 
Video demonstration [here](https://github.com/eranif/codelite/files/4315169/codelite-issue.mp4.gz). (Recorded on v13.0.0, but the issue is still present after upgrading). It seems to work only half of the time.

**Comment by krthkj** [comment]
Copy-paste in CodeLite using keyboard is literally unreliable and frustrating.

- CodeLite 14.0.0
-  wxWidgets 3.0.4
- GTK 3.24.13 and 2.24.32 (both installed)
- Gnome 3.34.2
- Pop OS 19.10

**Comment by btprg** [comment]
The same problem.
¤ CodeLite 13.0.0
¤ wxWidgets 3.0.4
¤ GTK 2.24.32 and 3.24.18
¤ Ubuntu 20.04 LTS

**Comment by akgupta0777** [comment]
How they can close this important issue before it is getting solved
This made me frustrated Codelite is so good C++ IDE that now I cannot stick to another IDE Please Fix this issue as fast as possible.

**Comment by dghart** [comment]
>How they can close this important issue before it is getting solved

It was closed automatically.

It sounds as if there are 2 different issues reported here: large pastes from CodeLite to other programs, and small pastes within it. I can't reproduce either of them, testing on:
-  debian buster (LXQT) with the latest CodeLite and wxWidgets versions, gtk+3.2.4.
- a standard ubuntu 20.04 install (in VirtualBox) with CodeLite 14.0, wxWidgets 3.1.3, gtk+3.2.4.

I appreciate that this sort of issue can be very annoying (I too get intermittent clipboard failures on debian and ubuntu, though not especially in CodeLite) but debugging it is impossible without first being able to reproduce it. If you can reproduce it in a standard ubuntu 20.04 or similar, please tell us how.

Even then, as eranif said, it's likely to be a wxWidgets issue that can't be fixed in CodeLite. I see there was  [a recent wx fix](https://github.com/wxWidgets/wxWidgets/commit/69e27acf0df03a4868c4012639428fb423a1c5f1) for something that sounds similar. That fix is in wx3.1.4 so I suggest you test CodeLite built with that.
