### ISSUE TITLE
Wrong package name in installation instructions for wxWidgets 3.1 GTK+3

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#2426]
https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries
`libwxgtk-media3.1unofficial3-dev` -> `libwxgtk-media3.1-unofficial3-dev`

**Comment by dghart** [comment]
Thank you for reporting this. There is indeed a problem, but it's not just a simple documentation issue.

Due to packaging errors, the gtk3 wxgtk3.1-media dev  packages _do_ have hyphens in some distro/versions, but not in others. Fortunately this doesn't matter for apt users (which is why I hadn't noticed) but it does make it hard to document what to wget.

I'll make sure this doesn't happen in future wx releases. Meanwhile I've added symlinks so that either name should work (and this doesn't seem to have bothered apt...).

Regards,

David

**Comment by AJenbo** [comment]
Interesting, I got an error when trying to run the given command (using apt).

**Comment by dghart** [comment]
Oh. What error, and what command were you running? And when? Before I added symlinks today, or after?

BTW, there aren't any 20.04 packages (yet) so...

**Comment by AJenbo** [comment]
`E: Unable to locate package libwxgtk-media3.1unofficial3-dev`

```
sudo apt-get install libwxbase3.1-0-unofficial3 \
                 libwxbase3.1unofficial3-dev \
                 libwxgtk3.1-0-unofficial3 \
                 libwxgtk3.1unofficial3-dev \
                 wx3.1-headers \
                 wx-common \
                 libwxgtk-media3.1-0-unofficial3 \
                 libwxgtk-media3.1unofficial3-dev \
                 libwxgtk-webview3.1-0-unofficial3 \
                 libwxgtk-webview3.1unofficial3-dev \
                 libwxbase3.1-0-unofficial3-dbg \
                 libwxgtk3.1-0-unofficial3-dbg \
                 libwxgtk-webview3.1-0-unofficial3-dbg \
                 libwxgtk-media3.1-0-unofficial3-dbg \
                 wx3.1-i18n \
                 wx3.1-examples
```

I got the error Feb 3td 16:50 CET. So that would be before afaik.

Good point, I added the Eoan repo.

**Comment by dghart** [comment]
>sudo apt-get install...

I see: you trusted that list ;) . When I said that apt should work, I meant: if you ask apt what is available, it will tell you what the package names are. I use synaptic, so I just have to search for libwx,  wx- etc. In a terminal, apt policy libwx* would work similarly.
