### ISSUE TITLE
Built-in console emulatr

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#246]
It would be great to have a built-in console for running programs (like eclipse) (atm, there's a console tab where I can see the command used to launch the program, but I can't see the programs' output there) - as an added bonus, lines from stderr could even be coloured in red (again like in Eclipse), very useful for seeing errors quickly. Would also prevent me from having to switch between CodeLite, the Terminal and my application. Also, the terminal window that pop-ups is too small, so lines wrap a lot more than they need to. All of these would be solved by having a built-in console emulator.

**Comment by eranif** [comment]
The current state of the emulator will not be modified in the foreseen future

**Comment by flederwiesel** [comment]
I would like to see this reopened, since at work I mostly work on command line programs. Of course, one could pull the terminal window onto a second screen, but since it keeps appearing on the main screen (on Windows as well as on Linux), this soon gets very annoying.

Since by now no built-in console is planned to be implemented, maybe you could leave me some hint how to start, since I am not familiar with wx.

Regards,
Tobias
