### ISSUE TITLE
Unable to build, debug or run program.

### ISSUE THREAD

**Issue by Gyanstark** [eranif/codelite#2490]
Hi! I recently shifted to CodeLight to program. I tried a basic hello world program to test the run.
What I encountered is I am unable to build,run, or debug the program. When I click these option, nothing shows up on the screen. Not even a message. Please help as soon as you can. Thanks..

**Comment by dghart** [comment]
Hi,

From your (rather limited) description, this doesn't sound like the sort of issue that should be in a bug-tracker. Instead I suggest you post on the [CodeLite forum](https://codelite.org/forum/), providing more detail that should include your platform, your CodeLite version, which programming language you use, what type of Workspace you created...  Ideally you should attach the Hello World project to your post so that it can be tested by other people, (unless it's one of the template ones provided, that are known to work).
