### ISSUE TITLE
copy/paste sporadic in Ubuntu 20.04

### ISSUE THREAD

**Issue by david9100** [eranif/codelite#2503]
CodeLite version 14.0.0
Ubuntu 20.04 (two different machines, same results)
bug is sporadic, but occurs more times than it does not.

**test case 1:**
highlight text, press ctl-c
place cursor at desired point of insertion, press ctl-v : nothing inserted

**test case 2:**
highlight text, press ctl-c
highlight existing text to be replaced, press ctl-v : existing text deleted and replaced with nothing

**test case 3:**
highlight text, press ctl-x : existing text cut (deleted)
place cursor at desired point of insertion, press ctl-v : nothing inserted

**test case 4:**
highlight text, press ctl-x : existing text cut (deleted)
highlight existing text to be replaced, press ctl-v : existing text deleted and replaced with nothing

**Comment by dghart** [comment]
Hi,

I've just tested 14.0 in a standard ubuntu focal virtualbox guest, and I couldn't reproduce the problem. Of course that's par for the course for intermittent bugs :(

A few comments:
Did you install CodeLite from our repository, or is your CodeLite self-built? If self-built, which wxWidgets version did you use to build it? (If you're unsure, you can find out by doing: Ctrl-Alt-Middleclick in a running CodeLite instance.)
I ask because afaik CodeLite doesn't implement clipboard things itself; it uses the wxWidgets toolkit for that sort of thing.

I tested a c++ file in a standard Workspace/Project, with an en_GB locale/lang. Is that similar to your failing case? If not, please test with c++, other locales... 

Have you previously used different CodeLite versions and/or different ubuntu versions without seeing the problem?

Finally, fwiw, on debian I've had intermittent clipboard issues in the past couple of years, both inside and outside CodeLite, after changing DE to lxde/lxqt. Apart from a known konsole bug, I suspect they are due to the DE and/or its clipboard.

Regards,

David

**Comment by sillick-rfa** [comment]
I am also seeing this bug. But on multiple versions of Ubuntu in a VMWare Workstation box. 19.10 and 20.04.

I installed from the CodeLite Ubuntu repository. Version 14.0. It says it uses wxWidgets 3.1.3
