### ISSUE TITLE
Permission denied message when doing cout using gnome & lxterminal

### ISSUE THREAD

**Issue by ti2to** [eranif/codelite#2507]
I am a new user.  Installed CodeLite yesterday. I have found on a forum that this issue was a bug on a recent previous version.  I am running CodeLite 14.0.0 on Ubuntu 20.04.   codelite-terminal neither show up. 
![Screenshot from 2020-05-18 12-31-46](https://user-images.githubusercontent.com/52167458/82260280-3542ef80-991a-11ea-852c-e7b7eb213bd8.png)

**Comment by ti2to** [comment]
I resolved issue by downgrading to Ubuntu 18.04 LTS and now CodeLite works fine.  Claudio

**Comment by dghart** [comment]
> I resolved issue by downgrading to Ubuntu 18.04 LTS and now CodeLite works fine.

That seems a slightly drastic solution ;)

I just tested CodeLite 14.0 in a ubuntu 20.04 virtualbox guest. After installing lxterminal and setting it as CodeLite's preferred terminal, a template project built and ran without any problem.

What happens if you try running /home/....../Project1/Debug/Project1 in a lxterminal instance outside CodeLite?

You could also try using Settings > Terminals: codelite-terminal instead of lxterminal...

**Comment by hichamhendy** [comment]
I am still facing the same issue and am not sure where the problem. I originally wrote the script on different OD version but I thought it would work automatically on a new version!!!

 
![Screenshot from 2021-05-20 11-01-59](https://user-images.githubusercontent.com/45830803/118950874-e085ea80-b95a-11eb-9ff1-676a28c6dddd.png)

**Comment by dghart** [comment]
> I am still facing the same issue

Are you sure it's the same issue? You don't mention a failure to find lxterminal...

Anyway, the correct place to ask for help about this is the [CodeLite forum](https://codelite.org/forum/), supplying more details of what you are trying to do and what is going wrong; in particular, the settings that result in that script being called.
