### ISSUE TITLE
Unable to start terminal for debugging in WSL2

### ISSUE THREAD

**Issue by KuDeSnik33ra** [eranif/codelite#2538]
I installed Windows 10 2004 and Ubuntu in Windows Subsystem for Linux, I used VcXsrv as XServer - in multiple windows mode (Linux app window is displayed as native window on windows desktop). Codelite started and compiled my solution normaly. But debugging start failed with message box "Failed to start terminal". I tried to select (and installed them, of course) half of available terminal variants in preferences, sometimes message box changed - "Terminal returned error 1" was added to it. Terminals itself works normally - started from console command. What can I do to fix this?

**Comment by dghart** [comment]
I don't use Windows so I can't offer detailed advice. But on Linux, the message means that terminal is no installed.

I realise you _have_ installed some terminals, but maybe they aren't being found. Instead, assuming you are using a recent CodeLite version, try using the built-in codelite-terminal.

**Comment by KuDeSnik33ra** [comment]
I tried codelite-terminal with same result. Is there any possible way to debug this - enable logging of debug session mabe? I looked to ~/.codelite/ for logs - there was two, nothing about this error in both.

**Comment by dghart** [comment]
Which CodeLite version are you using? There have been considerable changes in the terminal code since (iirc) 12.0.

You can set maximal logging in Settings > Preferences: Misc > Log and select Developer. Don't be surprised if that doesn't help, though.

Otherwise I can't think of anything easier than running CodeLite in a debugger and putting breakpoints in e.g.
[clConsoleGnomeTerminal.cpp](https://github.com/eranif/codelite/blob/master/CodeLite/clConsoleGnomeTerminal.cpp), the code of which is used by other terminals too; in particular clConsoleGnomeTerminal::FindProcessByCommand.

**Comment by KuDeSnik33ra** [comment]
Codelite version is 13, Ubuntu 20.04
Logging = drveloper gives only this:
ZombieReaperPOSIX: process 31121 exited with status code 0

**Comment by KuDeSnik33ra** [comment]
I think, what problem is in terminal code, not CodeLite - is there any log for codelite-terminal?

**Comment by dghart** [comment]
>I think, what problem is in terminal code, not CodeLite

But:
>Terminals itself works normally - started from console command

If (for example) lxterminal runs successfully when started _outside_ CodeLite, the terminal can't be the problem. It must be how CodeLite is starting it or (more likely) how CodeLite is failing to detect that it's successfully running; which is why I mentioned clConsoleGnomeTerminal::FindProcessByCommand.

>is there any log for codelite-terminal?

Clearly not, or you would have seen logged output.

**Comment by dghart** [comment]
Oh, and try [updating](https://wiki.codelite.org/pmwiki.php/Main/Repositories#toc1) to CodeLite 14.0, which had terminal-detection improvements.

**Comment by KuDeSnik33ra** [comment]
v14 = same problem. I tested debug built codelite 14 form sources.
Terminal selection property gives only codelite-terminal, and codelite-terminal is crashing with call stack:

**Comment by KuDeSnik33ra** [comment]
Why there aro not other terminals options available?

**Comment by eranif** [comment]
I tried the setup you mentioned, and for me CodeLite offers a list of terminals.
I also tried to debug, and again the result was the same: my selected terminal (`xfce4-terminal`) is launched and I am able to debug

![windows-ubuntu](https://user-images.githubusercontent.com/3677711/87238013-c065d080-c405-11ea-82dd-fcef1440baec.png)

**Comment by KuDeSnik33ra** [comment]
What is your Linux distro? I used Ubuntu 20.04. What is your desktop environment (xserver)? I used remote vcxsrv on windows - to have Linux app windows separately on win10 desktop, not as one Linux desktop in a window with app windows nested in it.
I followed instructions [here](https://www.reddit.com/r/bashonubuntuonwindows/comments/fmul2g/wsl2_on_win10_with_gui_apps_under_ubuntu/)

>CodeLite offers a list of terminals.

In normal mode - installed from apt package, I also have a list of terminals. But then I done debug-build Codelite from latest sources (github - master) - by this [ref](https://wiki.codelite.org/pmwiki.php/Developers/Linux), and have only one terminal available in the list.
