### ISSUE TITLE
CodeLite 14.0.1 crashes when opening or creating new workspace on MacOS 10.15.4

### ISSUE THREAD

**Issue by irahorecka** [eranif/codelite#2542]
Whenever I try to open or create a new workspace in CodeLite, the software exits without any traceback log. Any suggestion would be helpful - thanks!

**Comment by eranif** [comment]
thanks for reporting this, I will check this.
Usually on macOS when a software exits, you get a crash report, can you post its content here?

**Comment by irahorecka** [comment]
The strange thing is that there is no crash report - it's as if the application exited cleanly. It might have something to do with my OS. I will try to reinstall the application and see if that resolves the issue

**Comment by irahorecka** [comment]
Ah okay, now the app opens, but then closes right away. There are no crash reports when the app shuts down, but I do see this pop up in my system.log when I try to open the application:

`Jul  8 10:56:19 iras-mbp com.apple.xpc.launchd[1] (com.eranif.CodeLite.12816[5580]): Service exited due to SIGPIPE | sent by CodeLite[5580]`

**Comment by eranif** [comment]
I just tried that on macOS 10.15.5 - works.
Try deleting the folder `~/Library/Application Support/codelite` and launch CodeLite again

**Comment by irahorecka** [comment]
Great - solved the issue. Thanks!

**Comment by dennydav00** [comment]
I tried the same on Ventura 13.4.1, but I could not find the codelite folder in the path mentioned. But there was another folder Code which i removed but didnt help.

**Comment by jalenarko** [comment]
@dennydav00 same

**Comment by eranif** [comment]
Please try to avoid opening **ancient** issues. Make sure you installed latest CodeLite from brew as described here:
https://docs.codelite.org/downloads/download/#macos

**Comment by jalenarko** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               codelite [3559]
Path:                  /Applications/codelite.app/Contents/MacOS/CodeLite
Identifier:            codelite
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-22 18:19:29.2149 +0200
OS Version:            macOS 13.4.1 (22F770820d)
Report Version:        12
Anonymous UUID:        24A11515-283A-0609-9F17-67D86418372A


Time Awake Since Boot: 760 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libjpeg.8.dylib
Referenced from: <E353338F-A1A5-3E35-9618-EFFBA1DD5430> /Applications/codelite.app/Contents/MacOS/libtiff.6.dylib
Reason: tried: '/opt/homebrew/*/libjpeg.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libjpeg.8.dylib' (no such file), '/opt/homebrew/*/libjpeg.8.dylib' (no such file), '/usr/local/lib/libjpeg.8.dylib' (no such file), '/usr/lib/libjpeg.8.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x198445118 __abort_with_payload + 8
1   dyld                          	       0x198450d7c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x198450db0 abort_with_payload + 16
3   dyld                          	       0x1983dc8a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x1983d9590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                          	       0x1983d7e18 start + 1964


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016fb55ca0   x3: 0x000000000000007f
    x4: 0x000000016fb558a0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000033  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x00000001983d535c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fb558a0  x21: 0x000000000000007f  x22: 0x000000016fb55ca0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001f3bf9100  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016fb55870   lr: 0x0000000198450d7c
    sp: 0x000000016fb55830   pc: 0x0000000198445118 cpsr: 0x00001000
   far: 0x0000000103074000  esr: 0x56000080  Address size fault

Binary Images:
       0x1002a8000 -        0x1005d7fff codelite (*) <0e753c46-5ae3-3ef5-a4cf-1c05e414bf65> /Applications/codelite.app/Contents/MacOS/codelite
       0x101700000 -        0x102037fff libwx_osx_cocoau-3.3.0.0.0.dylib (*) <410804a6-0067-3635-8c3c-2b4401b924ea> /Applications/codelite.app/Contents/MacOS/libwx_osx_cocoau-3.3.0.0.0.dylib
       0x100f2c000 -        0x10132ffff libplugin.dylib (*) <ef7eb56d-f4a3-3435-a41f-080f84daffad> /Applications/codelite.app/Contents/MacOS/libplugin.dylib
       0x10254c000 -        0x10278bfff liblibcodelite.dylib (*) <484fc191-cd37-3dff-a8e0-f5bf626dcecf> /Applications/codelite.app/Contents/MacOS/liblibcodelite.dylib
       0x100900000 -        0x10090ffff libwxsqlite3.dylib (*) <c1a60327-2cd3-3619-b913-dfd30fdb74c9> /Applications/codelite.app/Contents/MacOS/libwxsqlite3.dylib
       0x100994000 -        0x1009dbfff libssh.4.dylib (*) <24b6a767-15f1-34a7-9bbd-9e06b0213875> /Applications/codelite.app/Contents/MacOS/libssh.4.dylib
       0x100a7c000 -        0x100ae3fff libpcre2-32.0.dylib (*) <180016c4-1c20-38bb-86d0-e94e01848dbb> /Applications/codelite.app/Contents/MacOS/libpcre2-32.0.dylib
       0x100af8000 -        0x100b57fff libtiff.6.dylib (*) <e353338f-a1a5-3e35-9618-effba1dd5430> /Applications/codelite.app/Contents/MacOS/libtiff.6.dylib
       0x100c30000 -        0x100cd3fff libzstd.1.dylib (*) <9cc1e4e5-da83-3b83-a1b9-b4f1ccc5d596> /Applications/codelite.app/Contents/MacOS/libzstd.1.dylib
       0x100958000 -        0x100977fff liblzma.5.dylib (*) <b0eb2993-ed5b-313b-8e4e-4f206b05ea68> /opt/homebrew/*/liblzma.5.dylib
       0x102d28000 -        0x102f63fff libcrypto.3.dylib (*) <5b1cbd59-7b5a-3c28-95e2-ef7c68029db7> /Applications/codelite.app/Contents/MacOS/libcrypto.3.dylib
       0x1983d2000 -        0x198460553 dyld (*) <2237410f-d39c-30ce-9a94-13aacb66b766> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=9840K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9840K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                             812K      195 
__AUTH_CONST                      17.1M      372 
__CTF                               824        1 
__DATA                            8669K      368 
__DATA_CONST                      19.6M      384 
__DATA_DIRTY                       962K      125 
__FONT_DATA                        2352        1 
__LINKEDIT                       811.5M       12 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2011K        1 
__TEXT                           389.4M      402 
dyld private memory                272K        2 
===========                     =======  ======= 
TOTAL                              1.3G     1867 



-----------
Full Report
-----------

{"app_name":"codelite","timestamp":"2023-07-22 18:19:29.00 +0200","app_version":"","slice_uuid":"0e753c46-5ae3-3ef5-a4cf-1c05e414bf65","build_version":"","platform":1,"share_with_app_devs":1,"is_first_party":1,"bug_type":"309","os_version":"macOS 13.4.1 (22F770820d)","roots_installed":0,"incident_id":"A6AD158E-BBAB-4D11-BD7E-B114518A22D5","name":"codelite"}
{
  "uptime" : 760,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,7",
  "coalitionID" : 1265,
  "osVersion" : {
    "train" : "macOS 13.4.1",
    "build" : "22F770820d",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-22 18:19:29.2149 +0200",
  "incident" : "A6AD158E-BBAB-4D11-BD7E-B114518A22D5",
  "pid" : 3559,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-07-22 18:19:29.1919 +0200",
  "procStartAbsTime" : 18459926210,
  "procExitAbsTime" : 18460381687,
  "procName" : "codelite",
  "procPath" : "\/Applications\/codelite.app\/Contents\/MacOS\/CodeLite",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.eranif.CodeLite",
  "crashReporterKey" : "24A11515-283A-0609-9F17-67D86418372A",
  "codeSigningID" : "com.eranif.CodeLite",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425857,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/opt\/homebrew\/*\/libjpeg.8.dylib","Referenced from: <E353338F-A1A5-3E35-9618-EFFBA1DD5430> \/Applications\/codelite.app\/Contents\/MacOS\/libtiff.6.dylib","Reason: tried: '\/opt\/homebrew\/*\/libjpeg.8.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/opt\/homebrew\/*\/libjpeg.8.dylib' (no such file), '\/opt\/homebrew\/*\/libjpeg.8.dylib' (no such file), '\/usr\/local\/lib\/libjpeg.8.dylib' (no such file), '\/usr\/lib\/libjpeg.8.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":26303,"threadState":{"x":[{"value":6},{"value":1},{"value":6169124000},{"value":127},{"value":6169122976},{"value":0},{"value":0},{"value":0},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":51},{"value":0},{"value":0},{"value":521},{"value":6849123164,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6169122976},{"value":127},{"value":6169124000},{"value":1},{"value":6},{"value":8384385280,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6849629564},"cpsr":{"value":4096},"fp":{"value":6169122928},"sp":{"value":6169122864},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6849581336,"matchesCrashFrame":1},"far":{"value":4345774080}},"frames":[{"imageOffset":471320,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":11},{"imageOffset":519548,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":11},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":11},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":11},{"imageOffset":30096,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4184,"imageIndex":11},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":11}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4297752576,
    "size" : 3342336,
    "uuid" : "0e753c46-5ae3-3ef5-a4cf-1c05e414bf65",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/codelite",
    "name" : "codelite"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4319084544,
    "size" : 9666560,
    "uuid" : "410804a6-0067-3635-8c3c-2b4401b924ea",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libwx_osx_cocoau-3.3.0.0.0.dylib",
    "name" : "libwx_osx_cocoau-3.3.0.0.0.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4310876160,
    "size" : 4210688,
    "uuid" : "ef7eb56d-f4a3-3435-a41f-080f84daffad",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libplugin.dylib",
    "name" : "libplugin.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4334075904,
    "size" : 2359296,
    "uuid" : "484fc191-cd37-3dff-a8e0-f5bf626dcecf",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/liblibcodelite.dylib",
    "name" : "liblibcodelite.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4304404480,
    "size" : 65536,
    "uuid" : "c1a60327-2cd3-3619-b913-dfd30fdb74c9",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libwxsqlite3.dylib",
    "name" : "libwxsqlite3.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4305010688,
    "size" : 294912,
    "uuid" : "24b6a767-15f1-34a7-9bbd-9e06b0213875",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libssh.4.dylib",
    "name" : "libssh.4.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4305960960,
    "size" : 425984,
    "uuid" : "180016c4-1c20-38bb-86d0-e94e01848dbb",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libpcre2-32.0.dylib",
    "name" : "libpcre2-32.0.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4306468864,
    "size" : 393216,
    "uuid" : "e353338f-a1a5-3e35-9618-effba1dd5430",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libtiff.6.dylib",
    "name" : "libtiff.6.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4307746816,
    "size" : 671744,
    "uuid" : "9cc1e4e5-da83-3b83-a1b9-b4f1ccc5d596",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libzstd.1.dylib",
    "name" : "libzstd.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4304764928,
    "size" : 131072,
    "uuid" : "b0eb2993-ed5b-313b-8e4e-4f206b05ea68",
    "path" : "\/opt\/homebrew\/*\/liblzma.5.dylib",
    "name" : "liblzma.5.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342317056,
    "size" : 2342912,
    "uuid" : "5b1cbd59-7b5a-3c28-95e2-ef7c68029db7",
    "path" : "\/Applications\/codelite.app\/Contents\/MacOS\/libcrypto.3.dylib",
    "name" : "libcrypto.3.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6849110016,
    "size" : 582996,
    "uuid" : "2237410f-d39c-30ce-9a94-13aacb66b766",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6848446464,
  "size" : 3551657984,
  "uuid" : "f5b60d87-3ee7-3c74-8415-517f8103a187"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=9840K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9840K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                             812K      195 \n__AUTH_CONST                      17.1M      372 \n__CTF                               824        1 \n__DATA                            8669K      368 \n__DATA_CONST                      19.6M      384 \n__DATA_DIRTY                       962K      125 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       811.5M       12 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2011K        1 \n__TEXT                           389.4M      402 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                              1.3G     1867 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "a8970941f35ea5cc6b6f6e1ebfd776513adaa6ff",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62c73fd17cce0d1b0bcb8a02",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "648719632dccf40610e755fa"
      },
      "deploymentId" : 240000137
    },
    {
      "rolloutId" : "6391cacc75b0720ff1f8c695",
      "factorPackIds" : {
        "COREOS_ICD" : "63957f508061fa721c8edc4a"
      },
      "deploymentId" : 240000007
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,7, BootROM 8422.121.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jan 12 2023 06:32:20 version 18.20.383.14.7.8.149 FWID 01-92e4bc4d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by jalenarko** [comment]
this is my report. i already uninstalled codelite and installed it again with your link and it was the same.

**Comment by eranif** [comment]
Thanks for this report, please use this issue instead:

https://github.com/eranif/codelite/issues/3230
