### ISSUE TITLE
My program doesn't run

### ISSUE THREAD

**Issue by Zkitto** [eranif/codelite#2599]
When I go to run a program, the output view says "Failed to start a build process", also at the bottom of the screen there are 3 blue dots who don't stop. How I can resolve? below I attach an image of the screen.
Thanks
![Screenshot **(6)_LI](https://user-images.githubusercontent.com/72996959/97304398-f4052300-185b-11eb-940b-edb7a9e0d85d.jpg)**

**Comment by eranif** [comment]
The problem here is that the command that CodeLite is trying to execute:
```
C:\Program Files\CodeLite /C C:/TDM-GCC-64/bin/ ...
```
the first part `C:\Program Files\CodeLite` should be (on most Windows system) `C:\Windows\system32\cmd.exe`
This can only happen if you manipulated the environment variable `COMSPEC`
Can you check it's value?
```
C:\Users\Eran>echo %COMSPEC%
C:\Windows\system32\cmd.exe
```
This is the proper value it should hold

**Comment by Zkitto** [comment]
@eranif Thank you, I'd change the variable COMSPEC to try something 👍 🥇
