### ISSUE TITLE
Regarding Edit

### ISSUE THREAD

**Issue by infinit-loop** [eranif/codelite#2625]
Backspace is not working in codelite. When I am creating a new workspace in codelite then editing the name of the workspace the backspace is not working.
Same problems occur for renaming the file.
Please help me....

**Comment by dghart** [comment]
>Please help me....

Please help _us_ by giving more information, so that we have a chance to test it ourselves:
Which OS are you using? Which version, distro etc?
What is your CodeLite version? Did you build it yourself (if so, against which wxWidgets version) or download it (if so, from where)?
What is your locale? Presumably not en_US...

What happens if you try doing a backspace inside a CodeLite editor? Does it work there? Are there any other keys that don't work correctly?

Are there any other apps on your system that have a similar problem?
