### ISSUE TITLE
Code gets deleted every time I build it

### ISSUE THREAD

**Issue by Jibrangit** [eranif/codelite#2638]
I am not sure when this started happening. If I download a source code and run it, it works perfectly. But if I so much as change a comment, it gives a build error. If I write a code myself, it gives a build error as follows.

What I have noticed, is that for some reason; after building, when I close the cpp file and reopen it, the file is empty; there's no code in it. I am not sure why this happening. I am attaching a snapshot of the error. What I have read online is that it occurs when someone doesnt put their code in main() and it makes sense, if the whole file is emptied of its contents, it would happen. But why?
![Issue_codelite](https://user-images.githubusercontent.com/73052263/104110179-090e2180-52a3-11eb-9745-d6774cf7de4b.png)

**Comment by dghart** [comment]
Hi,

That sounds strange!

First, some more information, please: Which CodeLite version? Which platform; it looks like Linux, in which case: distro/version? What happens with code that you *don't* download: code that you load from a file on your system, or enter yourself?

What happens if you download the code, but don't build it: just view it, change it a little, save it, close the file then reload.

Finally, it sounds rather like /tmp behaviour. When you download the file, where is it saved to? Is it possible that your 'downloader' saves it somewhere else, not inside ~/Documents/, a place where you don't have write permission?
