### ISSUE TITLE
Codelite uses ~5% CPU while idle. 

### ISSUE THREAD

**Issue by mparuzel** [eranif/codelite#2692]
Updated from v14 to v15.0.1. CPU levels hover somewhere between 2-6% while not using the application. Logs do not show anything out of the ordinary. I unloaded the workspace (only thing visible is the Welcome! tab) and CPU usage has not changed.

OS: Manjaro 64-bit, cinnamon DE, Xorg.

Reproduction: Start codelite and observe htop.

![codelite cpu](https://user-images.githubusercontent.com/16279440/111479266-2f1eca80-8707-11eb-858b-24230990490b.png)

**Comment by dghart** [comment]
Hi,

CodeLite has 'always' used a chunk of cpu: it silently does various things in worker threads. Until a couple of years ago the figure for me would have been >6%.

Out of interest, is that a significant change from 14.0?  For me, 14.0 on 1 machine is 2-2.3%;  on another, 15.0.1 is 3.6%.

Regards,

David

**Comment by mparuzel** [comment]
I only noticed this because it's enough to start the fans on my laptop. On 14.0 my idle laptop was silent. What I find curious is that when there is no workspace loaded, what exactly is codelite doing? No doubt this would put a dent into laptop battery life.

**Comment by eranif** [comment]
most of the CPU is caused because of wxWidgets. The (UpdateUI events mainly)
running a [poor man's profiler](https://www.oreilly.com/library/view/mastering-embedded-linux/9781787283282/23a8473f-d0d6-4113-a1cc-0c4aca1c9a5a.xhtml) will show that all of the worker thread are idle except for the main thread which spins in wxWidgets code... with no CodeLite source code in the middle
