### ISSUE TITLE
Makefile generating in wrong directory

### ISSUE THREAD

**Issue by Kylogias** [eranif/codelite#2713]
When you start a new project, it generates a makefile inside your workspace directory. However, when you try to compile said project for the second time (easiest to see if you make changes), the makefile (which belongs inside the workspace directory) is generated inside the project directory. I suspect that CodeLite keeps the current directory across runs. I'm on CodeLite 15.0.0 using MinGW-W64 with an Intel i7-10700K, GTX 1660 TI, 32 GB RAM.

To reproduce:

Make a new project
Check the newly generated makefile in the Workspace directory
Compile the project, or at least try to
Make some changes
Try compiling
Now look at the makefile in the Project directory

EDIT :: Current workaround would be adding "cd .." into the post-build section in the project properties

**Comment by eranif** [comment]
Can you please be more specific about how to reproduce this and what is the problem? from your post, I do not understand what is the problem (Makefile location is not an issue, if your code compiles) nor how to reproduce this.

In particular, please include **all the steps** and selections I should take in order to reproduce this (whatever "this" is), for example, in your previous post you mentioned that I should

> Make a new project

I cant really make a new project, unless I have a workspace first, right? or, there are multiple project types and multiple makefile generators, which option should I choose in order to see the problem? (which I don't clearly understand from this issue report)

Also, include what is the expected result vs the actual result

FYI: I did what you mentioned above (I completed the missing steps by guessing), and my workspace got compiled properly before and after changes (I don't really care about the Makefile location)

And how is the `post-build` section fits here?

**Comment by Kylogias** [comment]
It's in a C++ workspace. Upon further testing, it appears CodeLite forgets to go back a directory if the build fails (like a syntax error). I am unable to reproduce it on existing projects (projects made in separate session) though. Apparently the post build doesn't go through in the first place if it can't compile. If you look in CodeLite's build console, it'll say something along the lines of unable to find directory.
