### ISSUE TITLE
Git repo contains CRLF in some files

### ISSUE THREAD

**Issue by stahta01** [eranif/codelite#2740]
I am trying in my free time to get the current codelite git repo to build under MSys2.
And, I have run across some files that contain CRLF instead of just LF as is normal for text files.
Example is "CodeLite/SocketAPI/clSocketBase.h". What is the correct thing to do to fix the file linefeed issue for this project? 
1. Submit the formatting changes when patching the file for other reasons 
2. Submit a single patch that fixes many/most/all of the files with linefeed formatting issues
Or some other option?

Tim S.

**Comment by eranif** [comment]
I am aware of theses differences. It also annoys me (now).
Usually, I prefer the lazy way (option 1 in your case)

A single big patch will affect file history on larger scale and I'd rather avoid that

**Comment by stahta01** [comment]
Thanks, I will fix the files each time I find an issues to fix.

Tim S.

**Comment by Eric-01** [comment]
There are also files that use tabs for indentation instead of 4 whitespaces. Or lines that should be empty but have a few leftovers in the form of tabs or whitespaces.

I have already started working on resolving all these issues, and have spent a lot of time on this. It is so painful to do. You can see what I managed to do in [this branch](https://github.com/Eric-01/codelite/tree/test) in my fork.

**Comment by Eric-01** [comment]
There are also files that use tabs for indentation instead of 4 whitespaces, lines that should be empty but have a few leftovers in the form of tabs or whitespaces, and redundant whitespaces/tabs at the ends of lines.

I have already started working on resolving all these issues, and have spent a lot of time on this. It is so painful to do. You can see what I managed to do in [this branch](https://github.com/Eric-01/codelite/tree/test) in my fork.

**Comment by stahta01** [comment]
The normal way is to use an git attribute file; named ".gitattribute" I think.
And, then fix the entire repo; but, this might look bad in the file history.
So, a lot of people fix the files one by one manually and then add the ".gitattribute" file to keep it fixed.

Tim S.
