### ISSUE TITLE
Really need some help with compiler PLEASE

### ISSUE THREAD

**Issue by dpcoder1** [eranif/codelite#2761]
Hello, 

I have exam on Wednesday June 23rd and I've been using codelite for this past semester (for 2 months now) all of a sudden this start to happen when I try to compile and run my program: (I've tried uninstalling codelite and reinstalling multiple times and have tried using the wizard in the 'help' section to create a new compiler with no spaces between the name of the compiler. Here is what Happens when I try compiling: 

![image](https://user-images.githubusercontent.com/86146399/122635878-4a0d2c00-d0b4-11eb-9fa4-5d91ed793348.png) 

![image](https://user-images.githubusercontent.com/86146399/122635931-92c4e500-d0b4-11eb-8c0b-7274d411b17e.png)

![image](https://user-images.githubusercontent.com/86146399/122635940-9a848980-d0b4-11eb-9e1e-cb53ab183d91.png)

I was wondering if anyone can please help me soon, I need codelite to continue practicing for the exam. I know that there are other things like vscode, but I've gotten so used to codelite and the theme that I feel more comfortable coding there. So if anyone can please help me ASAP it would be greatly appreciated 

Thank you

**Comment by eranif** [comment]
This error message means that your project is using a compiler that is not configured by CodeLite.
open the `project settings -> general`, under `Compiler` you will the name used: 
`MinGW (mingw64)` (I think that in your case it will be empty, because it does not exist)

Now, in the project file, this compiler is set as the compiler to use, but CodeLite could not find it, this means that you probably messed your initial setup.

Go to `Settings -> Build Settings` and you will see the list of compilers you have.
You can:

- Copy one of them to the required by your project (i.e. `MinGW (mingw64)`
- In the dialog that is shown, CodeLite actually tries to help you: it basically tells you: "look, your project is requesting the compiler `MinGW (mingw64)`, but I cant find it. Do you want me to use a different one?" - so just select a different compiler

**Comment by dpcoder1** [comment]
Hello,

Thank you for getting back quickly. But when I go to settings and then Build settings this is what I see:

**Comment by eranif** [comment]
Try re-configuring CodeLite, use this guide:

https://docs.codelite.org/settings/build_settings/

**Comment by dpcoder1** [comment]
Hello,

So the first option didn't seem to work so I tried the manual option but when I tried to add this step:
![image](https://user-images.githubusercontent.com/86146399/122636713-a6724a80-d0b8-11eb-90ca-4852f464c483.png)
my codelite just simply crashed

**Comment by eranif** [comment]
- Close CodeLite
- Delete the folder `%appdata%\CodeLite` (or rename it)
- Start CodeLite

**Comment by dpcoder1** [comment]
By delete folder does that mean uninstall or something else?

**Comment by eranif** [comment]
No, just delete it (or rename it)
CodeLite is installed under `C:\Program Files\CodeLite`, the above folder is used for storing settings. Deleting this folder will cause CodeLite to start fresh as if you just installed it for the first time. Uninstalling CodeLite does remove this folder, unless you specifically asks for it

**Comment by dpcoder1** [comment]
When it says "Would you like to keep your local settings" should I press no then?

**Comment by eranif** [comment]
Yes :) (it does exactly that)

**Comment by dpcoder1** [comment]
IT WORKED!!! THANK YOU SO MUCH!

**Comment by dpcoder1** [comment]
Wait, quick question though. When I go back to the workspace that my codelite wasn't working on it prompt for the same thing. But when I am in a new workspace I can compile the code
