### ISSUE TITLE
Support search and replace libraries

### ISSUE THREAD

**Issue by elfring** [eranif/codelite#2845]
The functionality “search and replace” is supported (in principle).
:thought_balloon: I propose to take libraries also for the combination of search patterns and corresponding replacement possibilities better into account.
How can the selection of desirable adjustments become easier and more powerful? :thinking:

**Comment by eranif** [comment]
I am being honest here: this is not going to be implemented, CodeLite is using wxWidgets library with minimal other external libraries . The effort of adding new library and make it compatible across 4 platforms, its just too much of work
So, assuming I am not going to implement this (and I wont due to lack of time and value from this feature)
I doubt if anyone else will do - and from my experience with this open source project - it wont happen
