### ISSUE TITLE
Option "Highlight current line number" inhibits (destroys) other features

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2888]
Option "Highlight current line number" inhibits other features when enabled

When option "Highlight current line number" is enabled - the following features does not work:

"Trim only modified lines"
"Edit margin" (indicate changed lines with colors)

Analysis:
It all boils down to the fact that the "Highlight current line number" feature uses the margin style for highlighting the line number.

But the margin style is already used by the Edit margin change coloring   :-/

That means that the current line highlighting will overwrite (trash) the edit margin change/color indication on changes lines.

Also when saving it means means that the OnSave event cannot find any lines with edit margin change indicators (as they are overwritten by the highlight current line feature) - and hence it does not try to trim the changed lines (as there is no lines marked with change coloring)

This is seen with CL-15.0.8 as well as latest build from master

Issue #2861 is related to this problem - only at that time I did not see the connection

**Comment by eranif** [comment]
I was aware of this forcing the "Hide Edit Margin" to true (I am actually doing this on purpose)
The problem is that I wanted to implement this feature, but wxSTC does not support this, so I had to use the 
the text margin, which happens to be the same as the "Edit margin"

I was not aware of it trashing the "trim-on-save"
The only solution I can think of: 
Try and implement the "Edit" margin using bitmaps (similar to how we have breakpoints on the left margin)
and use this to re-implement the "trim-on-save" feature

**Comment by eranif** [comment]
A quick update on this one (not directly related):

I fixed a rather more urgent issue with this feature: it had a really bad performance. Opening a big files (try `sqlite3.c` for example) could make the editor hang terribly. With the recent git master this issue was completely resolved and the performance is not constant, regardless of the file size. 

With this fix, I also made this feature (i.e. `Highlight current line number` the default) - so you can expect a fix to come for the `Edit margin` as well

**Comment by eranif** [comment]
@uffejakobsen here is a proposal of a compromise:

![edit-margin-proposal](https://user-images.githubusercontent.com/3677711/147507800-d3111e1b-8d9f-4bb2-9b13-a1b6b65ccb1f.png)

**Comment by uffejakobsen** [comment]
@eranif I think that this is a good compromise :-) :+1:

**Comment by eranif** [comment]
note that on linux the red colour is a bit different (the above screenshot was taken on Windows)

**Comment by uffejakobsen** [comment]
Thanks :+1:
I guess this issue can be closed
