### ISSUE TITLE
GDB No Breakpoints No Longer Work on Cygwin

### ISSUE THREAD

**Issue by ksdhans** [eranif/codelite#2931]
I updated Cygwin, and now breakpoints are no longer working when debugging from CodeLite. The debug console outputs that the breakpoint has been set, but it never stops at the breakpoint.

Breakpoints work just fine when I use GDB from the command line, so GDB itself is okay.

I've tried:
- Upgrading to the latest CodeLite weekly build (15.0.9)
- Downgrading GDB from v10.2 down to v9.2 & even v8.3.1

None of it makes any difference. With GDB 9 it did stop at the breakpoint, but CodeLite then removed the breakpoint marker and didn't show which line it was at. 

All in all, rather confusing...

**Comment by eranif** [comment]
Can you elaborate on do you integrate with Cygwin / CodeLite?
- How do you start CodeLite? is it from the cygwin shell or from desktop icon
- Toolchain setup in CodeLite? (settings -> build settings)
Steps to reproduce

**Comment by ksdhans** [comment]
I start CodeLite from within Cygwin, and the build settings point everything to Cygwin's compilers & GDB as per the instructions on how to use CodeLite with Cygwin. I've had that working fine for years. That is, until today. The only thing that changed is that I recently updated Cygwin, including GCC, GDB, etc.

Steps to reproduce:
- Start Codelite from Cygwin
- Add a breakpoint
- Run the debugger

**Comment by eranif** [comment]
OK, I think I see the problem.

I tried to follow your instructions, and I can tell you that CodeLite is not cygwin friendly :(
Primary reason for this: I don't use Cygwin myself.

On the good news: we are working on porting CodeLite to cygwin so you can install directly from your package manager without the Windows installer (it will be using GTK3 instead of Windows native UI)

To the issue at hand:

It all sums up to the file paths are not being translated properly by CodeLite

For example, when gdb stops (breakpoint hit) it reports this:

```
DEBUG>>*stopped,reason="end-stepping-range",frame={addr="0x00000001004010a3",func="main",args=[{name="argc",value="1"},{name="argv",value="0xffffcc30"}],file="C:/Users/eran/Documents/TestCygwin/TestCygwin/main.cpp",fullname="/cygdrive/c/Users/eran/Documents/TestCygwin/TestCygwin/main.cpp",line="6",arch="i386:x86-64"},thread-id="1",stopped-threads="all"
```

At this point, what CodeLite will:
- Remove all visual breakpoints from the current editor
- Add breakpoints as reported by the debugger - this is so CodeLite in GDB will be in sync

So CodeLite removed the breakpoints **markers** successfully 
For next part: it tried to add the new breakpoints reported by GDB, but it could not locate a file with this path `/cygdrive/c/Users/eran/Documents/TestCygwin/TestCygwin/main.cpp`

so what changed?

This commit: 

https://github.com/eranif/codelite/commit/457d93a7a143f7dde389651af4dddf34cddc4c84#diff-99514d37c14fa5114eca2bfcd84cddabb1fded9af89489a750483ba7bd8808fdR155

before this commit, CodeLite was reading the file path from the `file` property of gdb reply, after this commit, I switched to `fullname` field - and in case of cygwin, the different is that `file` will report Windows' style path, while `fullname` will report the Cygwin path style

**Comment by ksdhans** [comment]
So, what can I do to get it working now? I tried rolling back to v15.0.0 (which, IIRC, also didn't work with GDB 10.2), but now get the error: "Could not find project configuration"

This problem has already cost me a day's productivity, so I'd really like it to be working again ASAP.

**Comment by ksdhans** [comment]
Okay, I got v15.0.0 to start the debugger again. I can confirm that it does NOT work with gdb 10.2 even though it predates the commit you pointed to.

**Comment by ksdhans** [comment]
CodeLite v15.0.0 & gdb v9.2 work together. Looking forward to the next update.

Thanks for your help.

**Comment by ksdhans** [comment]
Actually, it still doesn't work right. Breakpoints are hit, but CodeLite gets the location wrong. I'm guessing that a GCC & GDB version mismatch might be at play. So, I still need a proper fix...

**Comment by eranif** [comment]
I can upload you a test build for testing purposes - let me know if this works for you

**Comment by ksdhans** [comment]
Sure. I'd be happy to test it out.

**Comment by eranif** [comment]
https://codelite.org/downloads/codelite/wip/codelite-amd64-15.0.10.exe

**Comment by ksdhans** [comment]
Still not working with GDB 10.2. 

I tried rolling back to GDB 9.2. Breakpoints are triggered, but it's still unable to locate the line in the source code. It will open the right file, though.

**Comment by eranif** [comment]
can you share the debugger log?

**Comment by ksdhans** [comment]
Here:
[CodeLite-GDB10.2-log.txt](https://github.com/eranif/codelite/files/7897407/CodeLite-GDB10.2-log.txt)
)

**Comment by eranif** [comment]
I see the problem:

```
DEBUG>>00000009^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x00000001004030b9",func="main(int, char const**)",file="Server/ZitaFTPServerMain.cpp",fullname="/cygdrive/d/Users/Hans de Ruiter/Development/Networking/ZitaFTP/Server/ZitaFTPServerMain.cpp",line="131",thread-groups=["i1"],times="0",original-location="main"}
```
in your workspace, the path set to `file` and this is why CodeLite failed to resolve it (probably some wrong working directory).
Out of curiosity, how do you build your workspace? is it by using some custom makefiles?

**Comment by eranif** [comment]
I added a better and more "correct" fix: I added new class that translates paths between cygwin <-> native windows paths
this class (`clFileName`) is now being used in the debugger to translate paths where needed. I tested some use cases and all seems to work, please give it another try

**Comment by eranif** [comment]
I have updated the installer https://codelite.org/downloads/codelite/wip/codelite-amd64-15.0.10.exe
same link, different build

**Comment by ksdhans** [comment]
Your fix works! I can set breakpoints and step through code again. Thanks.

Yes, this project has a custom makefile.
