### ISSUE TITLE
Ctagsd dont parse dependencies

### ISSUE THREAD

**Issue by alex-rass-88** [eranif/codelite#2949]
Ctagsd dont parse dependencies what added in "Include Paths".
Temporary i add paths to ctagsd.json (search_path) by hands and it works.

**Comment by eranif** [comment]
It suppose to
`ctagsd` reads the addition paths (you shouldn't mess with them) from the `compile_flags.txt` or `compile_commands.json` files
You should perform at least one build on your workspace to ensure that this file is generated properly. 
Once CodeLite will generate it -> it will restart `ctagsd`  automatically to load the changes.

FYI:
The restart occurs only there were real changes since the last time it was generated

**Comment by alex-rass-88** [comment]
Hm... I add /usr/include/SDL2 to includes. It present in compile_commands.json but not in compile_flags.txt.

**Comment by alex-rass-88** [comment]
If use clangd it works.

**Comment by eranif** [comment]
You should only have one of these files.
It it exists in `compile_commands.json` and not in `compile_flags.txt` it means that your CodeLite is configured to generate `compile_commands.json` files. Disable this options from `settings -> code completion`
once disabled run a new build and your `compile_flags.txt` files should get updated.

`ctagsd` will always prefer `compile_flags.txt` over `compile_commands.json` file. If you want it to use `compile_commands.json` instead, delete the file `compile_flags.txt`
