### ISSUE TITLE
Codelite Debian Bullseye version crashes on startup.

### ISSUE THREAD

**Issue by oliverhbailey** [eranif/codelite#3012]
Hello,
I just attempted to install Debian Bullseye repository vesions of codelite and codelite plugins.  When I ran it the first time, it immediately crashed on startup. So I removed the codelite and codelite-plugins using apt purge and reinstalled it again.  It is still crashing at startup.  I did a version check and it is version 14.0.0.  Is there a command line switch to recreate or overwrite startup files?

**Comment by eranif** [comment]
Hi Oliver,
You have 3 options: 

- Close CodeLite, delete the folder `~/.codelite` and start CodeLite again (If you can use the 2 other options I specified here, use it)
- Installer a later version of CodeLite (v14 is like 2.5 years old). You can obtain it from our respositories: https://docs.codelite.org/downloads/download/#setup
- Build CodeLite from sources, instructions can be found here: https://docs.codelite.org/build/build_from_sources/#linux

**Comment by dghart** [comment]
Hi,
> Is there a command line switch to recreate or overwrite startup files?

There's --datadir=<some-path> to create/use a different configuration.

I just installed the official Bullseye CodeLite 14 and plugins packages; CodeLite ran successfully. However that was in a VirtualBox guest that had previously been running a later CodeLite version, so it's still possible that you are missing a dependency.

What happens if you run it in a terminal? Any interesting output?
Did you try running it inside gdb?
Did you try ldd?

Regards,

David

**Comment by oliverhbailey** [comment]
Hello Eran,
When I went to build from source, I encountered the error reported in your
ticket number 2998.  I have attached the error log from the latest
downloaded version of codelite.  That folder was deleted when I uninstalled
version 14, bbut these errors are the same for both versions. My desktop on
this machine is xfce, and I do use Glade and gtk3 development libs are all
installed.

Thanks,
Oliver

**Comment by oliverhbailey** [comment]
When I followed the instructions on adding the current codelite
repositories to Debian 11, I got the following errors.
***@***.***:~/wxWidgets$ sudo apt install codelite
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 codelite : Depends: libc6 (>= 2.34) but 2.31-13+deb11u3 is to be installed
            Depends: liblldb-14 but it is not installable
            Depends: libstdc++6 (>= 12) but 10.2.1-6 is to be installed
            Recommends: lldb (>= 3.4) but it is not going to be installed
            Recommends: clang-tools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
***@***.***:~/wxWidgets$

I just wanted to let you know.

Thanks,
Oliver Bailey

**Comment by dghart** [comment]
> When I followed the instructions on adding the current codelite repositories to Debian 11, I got the following errors....
Depends: libc6 (>= 2.34) but 2.31-13+deb11u3 is to be installed
Depends: liblldb-14 but it is not installable

Those look more like debian 12 versions. The 16.0 packages for debian in our repo are for 10 and 11 only.
Are you sure you didn't somehow manage to add one of our ubuntu lines e.g. jammy?

Or might you have tried to install the [offical debian 16.0 packages from 'testing' or 'unstable'](https://tracker.debian.org/pkg/codelite)?

**Comment by oliverhbailey** [comment]
Hi Eran,
Below s the release info I just typed.

***@***.***:~/codelite/build-release$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye
***@***.***:~/codelite/build-release$

As you can see, it is Debian 11.

Regards,
Oliver

**Comment by dghart** [comment]
>Hi Eran,

Did you mean me?

>As you can see, it is Debian 11.

I'm sure it is. But which _package_ are you trying to install? Its deps look more like those for debian 12, or ubuntu jammy, or...

What are your relevant /etc/apt/sources.list (etc) lines?

**Comment by dghart** [comment]
I think we're talking at cross purposes. I agree that debian 11 (bullseye) has [2.31-13+deb11u2](https://packages.debian.org/search?suite=bullseye&section=all&arch=amd64&searchon=names&keywords=libc6) and that's what's installed in my VirtualBox guest, which is what I used to build the bullseye CodeLite 16 package. 

However you are trying to install a different CodeLite package, which depends on libc6 (>= 2.34). That's why I'm asking about your /etc/apt/sources.list which is presumably what holds the relevant (wrong?) setting.

**Comment by oliverhbailey** [comment]
I found the problem...

When I added the line with your libraries for Debian 11, I chopped off the
"l" in the "devel" .  I went to to etc/apt/spurces.list, noticed the
missing "l" and it installed and is running properly.  I am still puzzled
by the list of packages it said wee the wrong versions. But once I added
the full word it now works.

Thanks David,
Take care.

Oliver Bailey

**Comment by dghart** [comment]
>I am still puzzled by the list of packages it said wee the wrong versions

Me too. But at least it now works :)

To revert to an earlier post:
>When I went to build from source, I encountered the error reported in your ticket number 2998.

That was in debian bullseye too, presumably. As you know, despite considerable testing I've failed to reproduce this, so I'm intrigued that you have found it too.
To help narrow down the possibilities, please could you describe your setup that failed. In particular, which version of wxWidgets were you building against, and where was it located? Inside /usr/, /usr/local/, or somewhere else?
What is the output of:
`update-alternatives --display wx-config
`
and what was your build command for CodeLite?

**Comment by oliverhbailey** [comment]
Hi David,
Let me share what I have done since this happened.

First, I have now tested this on the system and gcc, g++, wxwidgets
wxframe, and wxdialog projects work perfectly.  That machine also has rust
installed and that works perfectly as well.

Interesting you mention wxWidegets.  I am also a big wxWidgets developer.
And I also use the github repository version which as you probaby know is
at 3.1.6 rc2.

After I sent you the response, I went to another machine and installed from
source. That machine has g++ 9 installed.  It aborted twice in different
places with g++ memory allocation errors when compiling wxWidgets.
So I followed the instructions to install the latest codelite version.
This system is running Mint 20.04. I followed the same instructions, this
time typing in the full devel name and everything installed and works
perfectly.

Being a bleeding edge wxWidgets developer, here is my take on this.

Frequently, wxWidgets release candidates will fail to compile without
errors.  I have found, being a 20+ year user of wxWidgets;  these errors
always go away on their own after a couple days if I do a git fetch in 48
hours.  I've tracked git changes in the past and have found updates that
fixed the issues wete posted after my prior git fetch command.

Since both systems work perfectly by properly spelling the update sources
for both Mint 20.04 and Debian 11, I believe this was simply an issue with
the wxWidgets 3.1.6 rc 2.

Codelite work identical on both systems.  I cannot explain why the
misspelling generated the errors, but I would again point to my misspelling
and wxWidgets, not Codelite.

We got past this and both systems work identically and produce the same
results.

We pay a penalty for using bleeding edge but wxWidgets is one of the stable
libraries even it it hiccops once in awhile.

Thanks so much for your due dilligence in this matter.  I really like what
you folks have done with Codelite.

Regards,
Oliver H. Bailey

**Comment by dghart** [comment]
I'm glad it's all working for you now. But I'm interested about when it _didn't_, as I can't reproduce the problem here.

You [reported](https://github.com/eranif/codelite/issues/3012#issuecomment-1144781532) that, when you tried to build CodeLite from source, compilation failed with the same AddTool() errors as #2998. I'd really like to be able to reproduce that here: to do so it would be a great help if you could tell me how it happened for you.
In particular, on the machine where the failure occurred: 
1) Which version of wxWidgets were you building against?
2) Where was it located? Inside /usr/, /usr/local/, or somewhere else?
3) What is the output of doing: `update-alternatives --display wx-config`
4) What was your build command for CodeLite?

**Comment by oliverhbailey** [comment]
Hello David,
I got the wxWidgets libraries to build successfully by removing the
$(nproc) and using -j (number of processes).  This worked on both
machines.  I have never used that environment variable before

Regards,
Oliver Bailey

**Comment by dghart** [comment]
>I got the wxWidgets libraries to build successfully by removing the
$(nproc) and using -j (number of processes).... I have never used that environment variable before

It's  not an env variable, it's a command: `$()` is the same as ``. So, if you have 8 cores,  -j$(nproc) is the same as -j8.

**Comment by dghart** [comment]
>Being a 20+ year user of wxWidgets, I as you build from the github
repository. 
...
This has been a bigger issues in recent months as wxWidgets prepares to
bump major version number.

I fear we're again at cross purposes: I'm trying to understand how CodeLite failed to build for you and the #2998 reporter, when it fails to fail here. For that I needed to know which wxWidgets version you were using, which you've now said was 3.1.6. Thank you.

But, more importantly, I need to know **where** on your computer wxWidgets was installed, and ideally how you built it (what options you passed to ./configure) and whether that machine had any other wxWidgets installation that might have contaminated the CodeLite build (that's why I asked about the output of update-alternatives).

And, most important, I need to know how you tried/failed to build CodeLite: on that occasion, what was your CodeLite build command, the line that includes `cmake -G "Unix Makefiles" ...` ?

**Comment by oliverhbailey** [comment]
Sorry for my late reply.
I solved the problem by downloading the latest version of Codelite.  wxWidgets is always installed in my home directory regardless of platform.  The Codelite version with Debian 11 is too old.  In fact, it hs other functional problems as well outside the issue with wxWidgets.  Once I downloaded the latest Codelite on all platforms,  it ran as it should once again. 
I work on a lot of things during the course of a week, and being retired I take a lot of time to play as well.  So sometimes it takes me a while to respond.

Take Care

**Comment by oliverhbailey** [comment]
David,
Have you tested the codelite installation with the i386 architecture flag
on?  The reason I ask is because this machine is setup for x86_64, i386,
and arm cross builds.  Sometimes when multiple architectures are chosen on
Debian it affects the versions of standard libs.

Oliver Bailey

**Comment by dghart** [comment]
> Have you tested the codelite installation with the i386 architecture flag on?

No, we stopped supporting i386 some years ago (and if I did, I'd use a separate VirtualBox guest).

> Sometimes when multiple architectures are chosen on Debian it affects the versions of standard libs.

Really? Or do you mean that different architectures may have different versions of a particular lib? If so, you need to take particular care with your cmake settings.

By the way, the the compilation error reported reported in https://github.com/eranif/codelite/issues/2998 that you experienced above is now [fixed](https://github.com/wxWidgets/wxWidgets/commit/7e1cbe8f79b537649f5472b23b4a1e5642b10cd1) in wxWidgets; it affected only xpm bitmaps, which may explain some of the trouble reproducing it.
