### ISSUE TITLE
[Bug]: link to "Eclipse Colour Themes web site" is broken

### ISSUE THREAD

**Issue by EmilySeville7cfg** [eranif/codelite#3080]
### What happened?

When I follow [this](http://www.eclipsecolorthemes.org/) broken link in [this](https://docs.codelite.org/settings/colours_and_fonts/) page I obtain:

![image](https://user-images.githubusercontent.com/42812113/193591153-6e729fd4-91c6-4756-9c07-88ccc71f8af8.png)

### Version

Other

### Operating system

Linux

**Comment by dghart** [comment]
I see what you mean. Searching found [this site](https://www.reddit.com/r/eclipse/comments/x259o0/httpeclipsecolorthemesorg_down/) saying that it's been down since June. However it also points to a partial back-up on [github](https://github.com/eclipse-color-theme/eclipse-color-theme/issues/290).

Please would you test that site and see if it works for you. If so, I'll alter the doc page.

**Comment by EmilySeville7cfg** [comment]
[https://eclipse-color-themes.web.app/](this) site works fine for me.

**Comment by dghart** [comment]
Thank you. I've changed the link to that site.

**Comment by eranif** [comment]
thanks for letting us know about the working website. I have updated the link in the code as well
