### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by alevtina-karashokova** [eranif/codelite#3144]
I'm translating the Codelite interface and it's not clear to me how to translate the 'At' and 'What' columns in the Breakpoints table (see the screenshot). Could anyone explain what they mean? 
![Screenshot_20230208_102545](https://user-images.githubusercontent.com/122361137/217484030-cffcc967-978b-488f-9e1b-1b222dcb62b0.png)

**Comment by dghart** [comment]
Hi,

(Perhaps the [CodeLite forum](https://codelite.org/forum/) would have been a better place to ask this.)

It's years since I touched that code, and I'm not sure of the answer. On testing, those columns don't seem to display any data.

However looking at the gdb docs, e.g. https://sourceware.org/gdb/onlinedocs/gdb/Set-Breaks.html, I think their meanings  are just literal: 'what' shows the function in which the breakpoint is located, and 'at'  contains the address: file and line number. See:
![GdbBreakpoint](https://user-images.githubusercontent.com/6452587/217570119-ec6e9c31-7e79-4d60-9080-e0d928e030ef.png)

Regards,

David

**Comment by alevtina-karashokova** [comment]
Thank you for your help!

**Comment by dghart** [comment]
Thank you for helping with the translation!
