### ISSUE TITLE
[Feature Request]: Integrated terminal

### ISSUE THREAD

**Issue by srb623** [eranif/codelite#3202]
### Describe your idea in details

In Visual Studio Code there is an option for an integrated terminal which sets the default directory to the directory of the project.  I cannot find this option in codelite and would find it useful given that I'd prefer to develop via custom make files (the subject of another feature request) and thus an integrated terminal where I can work would be a good feature.

**Comment by eranif** [comment]
Note: I am closing this feature request since its basically implemented, but new features will be added to the terminal:

- Set the workspace folder as the terminal directory
- Allowing to choose default interpreter on Windows (e.g. using MSYS2's bash or WSL bash)
- Support multi terminals using tiled layout, similar to Tilix emulator (side by side)

**Comment by eranif** [comment]
Another small update on this one, here is how it looks now:
![terminal5](https://github.com/eranif/codelite/assets/3677711/2955cb49-2cc6-41ab-9d8d-9aa62a17f0a2)
