### ISSUE TITLE
(C++) Pressing Enter below "public:" adds unnecessary whitespace

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3235]
Consider the following code:

```
class MyClass
{
public:
private:
}
```
In above code, suppose we want to add a constructor for "MyClass". Putting caret after "public:" or before "private:" and pressing "Enter" key, CodeLite would modify the above code to this (add unnecessary 4 spaces before "public:"):
```
class MyClass
{
    public:

private:
}
```
It does so independently of tab width (which is set to 2). This can be undone by invoking Undo or pressing Ctrl + Z, but each time you press "Enter" to add another blank line, CodeLite will add unnecessary whitespace again. It will stop doing so once the actual constructor declaration is added, e.g.:
```
class MyClass
{
public:
  MyClass() = default;

  // Pressing Enter here no longer creates unnecessary whitespace for "public:"

private:
}
```
This is minor annoyance but is does affect productivity. It would be best if this annoying behavior could be disabled, or at least if there would be an option to tell CodeLite to stop doing that.

**Comment by paulhuman** [comment]
This is not an IDE problem. This is how the code is formatted by the С++ code formatter called clang-format. Check out .clang-format file in your project folder or workspace folder. You can customize the formatting rules to suit your needs. These tools can help: https://clangpowertools.com/clang-format-editor.html and https://zed0.co.uk/clang-format-configurator/

**Comment by paulhuman** [comment]
"clang-format leaves visibility modifiers at the same level as the class declaration".
This depends on the selected preset, which has its own default settings, as well as the settings that override the selected preset. Here are the presets: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#basedonstyle
CodeLite doesn't even use **BasedOnStyle** rule for the base preset, only custom rules.
Try removing/moving the .clang-format that CodeLite generates and start from the bare minimum. First decide on the preset that suits you best out of all the available standards. I use **LLVM** preset. Then you can override the rules you don't like. And you may omit 3 dots at the end. Sometimes clang-format can't interpret the file because of those dots at the end. I don't know why yet.
![bare_min](https://github.com/eranif/codelite/assets/14587675/cddc9d4a-667e-41ce-a054-15c14a2a26ad)

I also make it so that one **.clang-format** file is applied on all projects that are part of the workspace. To do this, delete the .clang-format files that are auto-generated in the project folders and place your own .clang-format file next to the ***.workspace** file.

I also like it when you save a file, the code is immediately formatted according to the rules. I checked the "**Format on save?**"
![format_on_save](https://github.com/eranif/codelite/assets/14587675/c11284d2-b91d-4cc2-a334-1ad51c6ba01d)

Try this file for debugging: https://raw.githubusercontent.com/dsp56300/gearmulator/dsp56300/source/.clang-format
I can see that the **public** and **private** modifiers jump out after hitting Enter, but after formatting they fall back into their places according to the rules. And I checked the behavior in Visual Studio 2022. Everything is fine here. The modifiers do not jump out.

**Comment by yunkot** [comment]
In my build, CodeLite doesn't generate ".clang-format" file anywhere. My "Source Code Formatter" settings page looks like this:
![Screenshot from 2023-08-17 12-27-07](https://github.com/eranif/codelite/assets/14065837/d005553d-ebb7-40ed-92be-fd0cf62b2b0b) (I'm using CodeLite built from sources, revision https://github.com/eranif/codelite/commit/cbbda264d37b389fe74bcba36c63f3c64c6ffcc1)

I am sorry, but I work with a big large code base, which uses company format conventions, so cannot use "clang-format" to format each file on save. Besides, it doesn't look like this issue has anything to do with "clang-format" because it happens even if I disable "Source Code Formatter" plugin.

As for Visual Studio 2022, I also use it and it doesn't exhibit this behavior. But this report is for CodeLite, not Visual Studio. It really looks like an issue of CodeLite's editor itself and I recall seeing this behavior in CodeLite for many years now. I am quite used to remove the blank space added by CodeLite each time, but as I've said in original post, this does affect productivity, especially in early prototyping stages, so I really hope it gets addressed eventually.

**Comment by paulhuman** [comment]
I use CodeLite 17.4.0 on Windows (monthly build released on July 18, 2023). I understand your discomfort. Little things like that can be annoying. Fortunately for me, my primary IDE is CLion. With new UI it's awesome.

**Comment by eranif** [comment]
@yunkot click on the `Defaults` button -> they will be scanned and appear
