### ISSUE TITLE
[Bug]: ctagsd is gone after new scan

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3250]
### What happened?

I did a new scan under LSP...

Before the scan the following LSPs were present: "clangd", "ctagsd" and "python"..
After the scan the following LSPs were present: "clangd", and "python"..

ctagsd is now gone - is that the correct behaviour ? (I guess not)

Seen with latest master on ArchLinux from this morning...

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
Not  a bug. By design. I prefer users not to use it. It is still being installed along with CodelLite
But if you really want to use it, you should configure it manually

All C++ users should be using `clangd` for code completion (`ctagsd` does not really up-to-date with the latest C++ language changes)

It was disabled in this commit:
https://github.com/eranif/codelite/commit/9bf629eeeb244a28bbbdf739936b720672d9b3eb

**Comment by uffejakobsen** [comment]
Ok thanks for the explanation...

But please correct my if I'm wrong - without ctags the `Open Resources` is more or less reduced to a "file-selector"...

At least on my current build of master  (without ctags) I'm unable to use `Open Resources` to go to a function inside another file...

**Comment by eranif** [comment]
Not really. It works nice for me.
Can you check your `clangd` version?

**Comment by uffejakobsen** [comment]
> Can you check your `clangd` version?

clangd version 16.0.6

My project is actually a remote project - but not controlled by codelite remote sync

Previously (with ctagsd) I was able to have ctagsd parse the files locally - even though that it will never be able to compile locally...

Now looking into clangd - I guess that clangd is unable to perform local indexing of something that is unable to compile locally...

This led me to try the codelite remote option - but that started a whole bunch of other problems.

I think that I'll close this issue and create separate issues/questions for my newly found troubles
