### ISSUE TITLE
[Bug]: Function is colored incorrectly when its name matches parameter of another function

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3266]
I'm using default configuration, so only clangd language server is present. In a situation, when some function has the same name as one of the parameters of another function, it will be colored as a parameter and not a function. The following example illustrates it:

![codelite-wrong-coloring](https://github.com/eranif/codelite/assets/14065837/daa9939d-4b09-4b0c-8d3e-4db7b8e0d391)

In above example, both "foo" and "bar" function names should have the same color and only "foo" parameter inside "bar" declaration should be colored as a parameter. I've seen this issue for many years already, but always thought that it was related to "ctags" parser. Shouldn't the coloring work correctly under "clangd"?

### Version

Self-compiled, revision 68d2333346c8120ff7c8dc2b8fdac420e358c6fb.

### Operating system

Arch Linux

**Comment by yunkot** [comment]
Also, the same issue occurs with enumerations: if you have a class named "Foo", and then you declare enum inside some class with the same name, it will be colored as a class and not as an enumeration.

**Comment by eranif** [comment]
This is a limitation with the underlying editing component. Internally, CodeLite uses wxSTC (wx port for https://scintilla.org). wxSTC allows the caller to pass list of tokens and assigne them with a style (each style can have font, colour etc). 
The LSP return coloring positions (e.g. token at line `X`, column `Y` with length `W` should be coloured with Function colours)

however, since wxSTC does not support colouring based on position, it actually keeps the token string in a list and then pass it to the editor for colouring.

So the same token appear in 2 lists: 1st time in the "function" list and another time in the "variable" list - and this causes the bug that you see
