### ISSUE TITLE
[Bug]: Only specific terminals work

### ISSUE THREAD

**Issue by nezos** [eranif/codelite#3273]
### What happened?

I built codelite to the current master version for VoidLinux. While trying to run a previous project that run in Codelite v16, I found out that it could not run since no terminal was found. I have xterm and lilyterm installed. The settings->preferences->terminal did not allow me to select anything, it was blank.

I then checked the code and found that there are only specific terminals allowed. I then manually changed the codelite.conf for rxvt-unicode (which I installed on my system). Even then I couldn't run it because in voidlinux rxvt executable is "urxvt". The only solution was to link rxvt-unicode to urxvt.

A good option would be to allow the user to specify the executables and avoid hard-coding them.

Moreover, a good thing would be to notify the user that none of the supported terminals were found rather than falling back to gnome-terminal that would not necessarily be installed.

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
the problem is that there is no unified command line arguments for specific parameters, for example, some terminals are using `-T` for setting the title and some `-t`, some will use `-d` and some will use `--working-directory` for setting the working directory

So, the approach I took was to manually support each terminal in CodeLite. If you have a specific terminal in mind, just let me know and I will add it.

For now, I have fixed the issue with RXVT since this was the trigger for this issue. If you have other terminals in mind -> please open a PR for a missing terminal that you think should be added to CodeLite
