### ISSUE TITLE
[Question]: How to start a blocking child process as a part of post build command

### ISSUE THREAD

**Issue by Cheese-S** [eranif/codelite#3464]
### What happened?

I have a server.sh that I need to launch as a post build command. 

I have tried the following

```./server.sh &```
```nohup ./server.sh &```
```server.sh > /dev/null 2>&1 &``` 

All of these hang and finishes building only when I manually kill the server process.

Is there a way to achieve this?

### Version

17.0.0

### Operating system

Linux

### Steps to reproduce

```text
none
```

### Relevant log output

```shell
none
```

**Comment by eranif** [comment]
I suspect that this is happening because the server is still a child process of the build process - so CodeLite "thinks" that it is still running (for good reason, usually, build processes launch multiple child process (make -> clang++ etc)

Did you try detaching it from the parent process? You can do this by using:

```bash
sudo apt install daemonize
daemonize <your program>
```
