### ISSUE TITLE
[Bug]: Working directory for custom builds ignored for files with compile errors

### ISSUE THREAD

**Issue by ttl-octave** [eranif/codelite#3551]
### What happened?

I have created a CodeLite project covering an existing codebase (C++). The build directory is a subdirectory of the project root and I have defined a working directory for the custom builds (make commands).

Whereas the build process works as expected, files with compile errors are not automatically opened in the editor. These files are correctly shown in the build output as relative paths based on defined custom build working directory. However, header files from libraries are correctly opened since they are shown with their absolute path.

The same issue shows up if I create a file system workspace where I have to define build commands like `cd .build && make` of `make -C .build`. Or is there a possibility to define a working directory for builds in file system workspaces?

### Version

17.0.0

### Operating system

Linux

### Steps to reproduce

```text
1. Define a working directory for custom builds as subdirectory of the project root
2. Force a compile error
3. Try to open the file from the build output (F4 or double click)
```

### Relevant log output

```shell
../libgui/src/gui-preferences-cs.cc:39:1: error: 'x' does not name a type
```

**Comment by eranif** [comment]
Could you upload a minimal workspace (with 1 makefile, 1 cpp file) that demonstrates the problem?

**Comment by ttl-octave** [comment]
Attached please find two minimal workspaces (C++ and file system):
1. [cl-test-ccw.zip](https://github.com/user-attachments/files/18247024/cl-test-ccw.zip): C++ workspace
2. [cl-test-fsw.zip](https://github.com/user-attachments/files/18247020/cl-test-fsw.zip): File system workspace

**Comment by eranif** [comment]
Thanks for this, will look into it

**Comment by eranif** [comment]
So the problem is:

- You are changing the working directory by using the command `cd build && make`
- CodeLite has no way of knowing that the working directory was changed to "build" (at least for the "File System Workspace")

With commit: https://github.com/eranif/codelite/commit/a0cdc60aa7c6e86fc28b09622cf736f99e4a8297

The problem for "C++ workspace" is fixed (CodeLite will now honour the custom build working directory)
For "File System Workspace":

Like I said, there is no way of knowing the working directory. However, I added a code that tracks the Make output "Entering directory" and "Leaving directory" - so CodeLite will attempt to convert the relative file path based on these messages.

In order to use this method, you will need to use:

```bash
make -C build
```

instead of:

```bash
cd build && make
```

**Comment by ttl-octave** [comment]
Thank you very much for the prompt fixes. I just built codelite from the current sources. Automatic file navigation work well now, for both, C++ and FS workspaces.
