### ISSUE TITLE
incompatible with ibus, invisible key break normal input 

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#38]
OS : Fedora 16 x86_64 English, all component is up-to-date.
codelite: 5375

there is 3 group key on keyboard:
    A.  visible-key:    a-z,0-9, Punctuation
    B.  invisible-key: Tab, Backspace, four arrow(left, etc), Insert, Delete, Home, End, PgUp, PgDn, Esc
    C. control-key:  Ctrl, Alt, Shift, Menu

while ibus is on(enable ibus in "Input Method Selector"):
    1. after you press any [B.  invisible-key],  the input is broken, you cannot input any [A.  visible-key] anymore. But invisible-key and control-key can input.break visible key input. 
    2. after normal input is broken, press any [C. control-key] can drag back temporarily, you can input all keys.

**Comment by DarrenCook** [comment]
This bug needs to be re-opened, as it is still happens. (I.e. latest 64-bit Mint 17, same as Ubuntu 14.04.2 LTS) I have exactly the same bug in GnuCash, and the fix in both cases is to do "ibus exit".
With GnuCash this is merely a Major Annoyance, as I need to do a logout/login to get ibus back. But with an IDE it is a fatal bug, as obviously there will be the need to input text strings in languages other than ascii.

**Comment by eranif** [comment]
Which version of CodeLite are you using? As this bug is known to be fixed for a long time now (almost a year now)
Also, I am using Linux Mint 17 myself with no issues...
If it is an iBUS bug, I can't really do anything about it...

See this forum post:  http://forums.codelite.org/viewtopic.php?f=3&t=2749&hilit=lose

**Comment by DarrenCook** [comment]
Version 7.0, freshly installed today, from the ubuntu repository. I just read that thread, and it does not seem to describe a fix: it just said to kill ibus to make the problem go away.
ibus IMEs work fine with every other program I have, except GnuCash, and now CodeLite. (I had a brief search, and I don't think GnuCash is built on wxWidgets, so it must be something else.)

If this is a Will Not Fix, perhaps you could put "won't work with ibus" in the compatibility section. (Perhaps on this page: http://codelite.org/LiteEditor/Repositories )

**Comment by DarrenCook** [comment]
More information: this bug is affecting the create new workspace input box, but not affecting the main editor window. If I run this way: `GTK_IM_MODULE=xim codelite` then the bug happens, and editing is horrible. But if I this way: `GTK_IM_MODULE=ibus codelite` then editing is fine, and also I can input Japanese (or whatever) as the workspace name.  (I just opened up bug #739 for the related, but very different, issues with the main editor window!)

This seems to be related to a bad interaction between GTK3 and xim: https://bugzilla.gnome.org/show_bug.cgi?id=645993    So I don't know if that is something that can be fixed in GTK3 apps, or not.
