### ISSUE TITLE
add support arduino projects

### ISSUE THREAD

**Issue by Fahreeve** [eranif/codelite#537]

**Comment by eranif** [comment]
We don't have the resources to implement this, please submit a PR if you really need it

**Comment by zozigizo** [comment]
Has anybody had any success with this: [https://github.com/sudar/Arduino-Makefile](url) ?

I'm trying it with Codelite setting `GNU makefile onestep build`

When calling makefile from Codelite:

`/usr/bin/avr-g++ -x c++ -include Arduino.h -MMD -c -mmcu= -DF_CPU= -DARDUINO=169 -DARDUINO_ARCH_AVR -D__PROG_TYPES_COMPAT__ -I/home/user/arduino-1.6.9/hardware/arduino/avr/cores/arduino -I/home/user/arduino-1.6.9/hardware/arduino/avr/variants/   -I/home/user/arduino-1.6.9/hardware/arduino/avr/libraries/SPI/src  -Wall -ffunction-sections -fdata-sections -Os -pedantic -Wextra -Wno-unused-variable -fno-exceptions -std=gnu++11 -Wno-unused-variable blink.ino -o /home/user/Arduino/project/bin/file.o
avr-g++: error: missing device or architecture after '-mmcu='`

When calling makefile without codelite (from command line):

`/usr/bin/avr-g++ -x c++ -include Arduino.h -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=169 -DARDUINO_ARCH_AVR -D__PROG_TYPES_COMPAT__ -I/home/user/arduino-1.6.9/hardware/arduino/avr/cores/arduino -I/home/user/arduino-1.6.9/hardware/arduino/avr/variants/standard    -I/home/user/arduino-1.6.9/hardware/arduino/avr/libraries/SPI/src   -I/home/user/workspace/Arduino/libraries/LedControl/src   -I/home/user/workspace/Arduino/libraries/SSD1306   -I/home/user/workspace/Arduino/libraries/edbox   -I/home/user/workspace/Arduino/libraries/edlib -Wall -ffunction-sections -fdata-sections -Os -pedantic -Wextra -Wno-unused-variable -fno-exceptions -std=gnu++11 -Wno-unused-variable blink.ino -o /home/user/workspace/Arduino/blink/bin/uno/blink/blink.o
`

The difference is variables are not passed on to included (sub) makefiles.

My suspect is the problem is: [https://github.com/eranif/codelite/issues/1097](url) but maybe somebody else have other suggestion?
