### ISSUE TITLE
Curly brackets on Linux Mint 17.1

### ISSUE THREAD

**Issue by fwsGonzo** [eranif/codelite#612]
{}
They do not work in the code window
They do work in search dialogues and all the other widgets

EDIT: Using Norwegian keyboard layout
The sequence is Alt Gr + 7 and 0 respectively

**Comment by hugin84** [comment]
any update/ETA on this? In this state CodeLite is kinda useless...
[Arch Linux 64bit, wxgtk 3.0.2-2, using Swedish and Norwegian keyboard layouts]

I can confirm the previous observations: 
- seems to affect all alt gr+[0..9] combinations (e.g. also '[', ']' -> alt gr+8/alt gr+9 respectively)
- only broken in code window
- was working in 6.1 (2014-08-16, commit 98fae0fb22b8860180abdea455809166f02a2ec3)

**Comment by eranif** [comment]
It looks like that something went bad with the introduction of the new keyboard shortcut manager
However, the simple workaround is to do this from the menu bar:
`Settings->Keyboard Shortcuts ->Defaults`

It fixed the problem for me

**Comment by hugin84** [comment]
unfortunately this didn't have any effect, I'm back on 6.1 for now

**Comment by eranif** [comment]
I just tried codelite 7.0 with Norwegian keyboard and it works fine for me (Ubuntu 14.04/64 bit)
Ofc, I am using OnBoard keyboard to test this.

Notice that I used a clean CodeLite 7.0 installation. To get the same effect of a "new" installation, just delete the folder: `~/.codelite` and see if it works for you

**Comment by eranif** [comment]
The problem seems to be related to how wxWidgets implemented the `AltGr` key,
According to this
```
/* This enum contains bit mask constants used in wxKeyEvent */
enum wxKeyModifier
{
    wxMOD_NONE      = 0x0000,
    wxMOD_ALT       = 0x0001,
    wxMOD_CONTROL   = 0x0002,
    wxMOD_ALTGR     = wxMOD_ALT | wxMOD_CONTROL,
    wxMOD_SHIFT     = 0x0004,
    wxMOD_META      = 0x0008,
    wxMOD_WIN       = wxMOD_META,
#if defined(__WXMAC__) || defined(__WXCOCOA__)
    wxMOD_RAW_CONTROL = 0x0010,
#else
    wxMOD_RAW_CONTROL = wxMOD_CONTROL,
#endif
    wxMOD_CMD       = wxMOD_CONTROL,
    wxMOD_ALL       = 0xffff
};
```
`AltGr` is mapped Control + Alt, so in your case `AltGr + 0` for `}` is captured by the External Tools plugin (which maps Control+Alt+0 for executing tool number 1, this goes from 0-9)

The simple solution is to remap the keyboard shortcuts from:
Settings->Keyboard shortcuts->Plugins->External Tools->External Tool 0-9

Or, you can unload the External Tools plugin from:
`Plugins->Manage plugins`, uncheck External Tools and restart CodeLite

**Comment by DesktopMan** [comment]
Changing the external tools shortcuts to ctrl+shift fixes 56789, but 0-4 triggers cscope actions.
