### ISSUE TITLE
Last session not restored

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#641]
Hi Eran,

using the latest git head on wxGTK, my sessions do not get restored anymore. That is,
the workspace is loaded, but not the files I left open when I closed CL. Was there a change
in that behaviour? It only seems to have started reecently.

Regards,
 René

**Comment by eranif** [comment]
None that I recall… 
I will test it here and see

**Comment by dghart** [comment]
In the last 24 hours I've been starting CL on various vbox guests. I noticed this issue once yesterday (I can't remember where and it disappeared after a reload). Today I seem to have it reliably in a jessie build.
I also had it once today on my (real) debian wheezy, but a reload succeeded.

I'm not saying it's directly connected, but the same problem happened a few weeks ago when the applying-new-theme dialog had been showing. That particular issue was fixed by e77ae8c, but there might be a similar situation again, presumably due to a race.

Regards,
David

**Comment by eranif** [comment]
Fixed in git master
