### ISSUE TITLE
Code completion context menu does not show when typing '.' or '->' or the scope resolution operator '::'

### ISSUE THREAD

**Issue by lavyadrian** [eranif/codelite#657]
Found on codelite 7 amd64 running on windows 7 64

**Comment by eranif** [comment]
Please provide a step by step example of how to reproduce this, as it does work elsewhere.
In general, this is not a bug but a configuration error on your side. Please report this on the forum and consult for assistance there

**Comment by lavyadrian** [comment]
Step by step? I installed the new version 7, ran it, typed one of the scope
resolution operators mentioned up there, and they didn't work anymore in
header files (.h in this case).

**Comment by eranif** [comment]
Step by step means:
1. Provide a minimal example of a workspace that shows the problem
2. An exact location where to try to type the scope resolution operator `::`

Anything that might help me here to simulate the problem, since it works for me...
So I need to understand what is the difference between our systems

**Comment by lavyadrian** [comment]
OK will get back to you on that.
