### ISSUE TITLE
Clang code formatter has odd default tab / space indentation settings

### ISSUE THREAD

**Issue by DesktopMan** [eranif/codelite#667]
Codelite 7.0. Editor -> Indentation defaults to "Use tabs in indentation" with a level of 4. Clang in general seems odd, in the example the first if is indented with spaces, but the return after it is indented with a tab. Shouldn't both of these follow the global editor setting?

**Comment by eranif** [comment]
The problem is with the "sample" code and not with clang-format
I think that TABS should be ban from the editor :)

The TAB vs Spaces is only set in the global editor settings (notice that there is no option to set this in clang).
If you will look at the source code formatter source file: https://github.com/eranif/codelite/blob/master/CodeFormatter/formatoptions.cpp

Notice the function at the bottom:
`wxString FormatOptions::ClangGlobalSettings() const`

**Comment by DesktopMan** [comment]
How is it a problem with the sample code when it formats my own code the same way?
Stuff this in main and the if is indented with spaces and the contents of it with a tab.

    if(true) {
	std::cout << "Yay, true!" << std::endl;
    }

**Comment by eranif** [comment]
:(
> How is it a problem with the sample code when it formats my own code the same way?
You should have started with this statement  :+1:

**Comment by eranif** [comment]
Maybe the solution for this is to convert the file to spaces <-> tabs before formatting is executed

**Comment by DesktopMan** [comment]
Seems like the result is the same if the code is formatted with all spaces or all tabs before it is run.

**Comment by eranif** [comment]
Can you upload a file that shows the problem?

**Comment by DesktopMan** [comment]
Here's a simple test file: http://bin.jvnv.net/f/vp4ZW/test.cpp

**Comment by eranif** [comment]
Ok, I see what you mean now, I did not see this because my settings are a bit different:
- I have indentation set to "spaces" (Global Editor Preferences->Indentation, uncheck "use tabs")
Hitting the Ctrl-I (format source code accelerator key) fixes this properly.
If, however, I enable the TABS to be the whitespace, I see what you mean

**Comment by eranif** [comment]
It looks like a bug in `clang-format` tool itself...
I installed `clang-foramt-3.5` on Linux Mint 17, and the results are the same, I also tried to strip all the options that CodeLite adds, the result is the same:
before the `if` statement there are 4 spaces, while the content of the `{...}`

**Comment by eranif** [comment]
Please report this bug to the clang mailing list
