### ISSUE TITLE
Failed to locate gdb! at '/usr/bin/gdb '

### ISSUE THREAD

**Issue by milottit** [eranif/codelite#670]
Version 7.0

When we start  the debugger, the following message appears : 
"Failed to locate gdb! at '/usr/bin/gdb '"

Even setting the absolute path of the gdb (for instance /usr/bin/gdb) in the GDB Settings doesn't fix the issue.

I found only one way to workaround the problem by setting the absolute path of gdb in the debugger settings of the project. (If there several project, each project has to fill the gdb path)

**Comment by eranif** [comment]
This bug was fixed already.
To fix this without your local workaround, you need to update the gdb in the toolchain and remove the extra space from it (notice the extra space in the error message) `at '/usr/bin/gdb '`

`Settings->Build Settings->COmpilers->Your compiler name->Tools->Gdb` and remove the extra space from the gdb path
