### ISSUE TITLE
Output view does not support mouse wheel

### ISSUE THREAD

**Issue by gbuntu127** [eranif/codelite#712]
Hi,

The output pane does not support middle mouse wheel, unless the cursor is on the scrollbar. 

I am using codelite version 7.1 on Linux Mint 17 Qiana. 
Codelite was built using the latest code form github (2015-4-2). 

Thank you for the great tool.

**Comment by eranif** [comment]
The mouse wheel is handled by wxWidgets (IOW: its out of my hands...)

**Comment by eranif** [comment]
FYI: I just remembered that we had this bug a year or 2 ago.
The problem was wxWidgets 3.0 that comes with the distro.

Which wxWidgets are you using? is it the one that comes with Mint? 
If it does, please replace it with the one that we provide, see here:
http://www.codelite.org/LiteEditor/WxWidgets30Binaries

The official wxWidgets has this bug: http://permalink.gmane.org/gmane.comp.lib.wxwidgets.devel/160621

**Comment by gbuntu127** [comment]
Yes, it is the one came with linux Mint. 
I will try with the suggested one, thanks.
