### ISSUE TITLE
Unable to change the command used to create the console window when debugging

### ISSUE THREAD

**Issue by jazztickets** [eranif/codelite#732]
Changing the setting under Global Editor Preferences -> Terminal only affects when you run the program (Ctrl+F5), not when debugging (F5)

**Comment by eranif** [comment]
This is by design. The debugger terminal is fixed and can not be changed.
It is done like this for various reasons (mostly because CodeLite interacts with the console)
Unlike when using a terminal for simple execution of a program.

If you want to have a more modern terminal, you can:

* Clone codelite sources and change it hardcoded to work as you want
* Customize `xterm` (which is highly customizable) to suit your needs. See this wiki page on our web site: http://codelite.org/LiteEditor/Linux-specificTheXtermDebuggerTerminal
