### ISSUE TITLE
vim mode

### ISSUE THREAD

**Issue by slycelote** [eranif/codelite#814]
Many editors/IDEs have vim editing mode, it would be great to see it in Codelite too.

**Comment by eranif** [comment]
This is unlikely to happen .. (Pull Request are most welcomed)

**Comment by hemantmits** [comment]
I would like to implement this feature. Any clue where I can start this?
Any existing plugin who's could I can refer for this?

**Comment by eranif** [comment]
Next, capture the event `wxEVT_ACTIVE_EDITOR_CHANGED` (which is sent when CodeLite sets the focus to a new editor)

In the 'ActiveEditorChanged' event handler, I would bind the active editor's `wxEVT_KEY_DOWN` event handler.

Resources:
[Create new plugin](http://codelite.org/Developers/CreatePlugin)
[List of all CodeLite events](https://github.com/eranif/codelite/blob/master/CodeLite/codelite_events.h)

**Comment by J2112O** [comment]
I would not mind joining in on getting this plugin up and going. I am new to C++ and want to use CodeLite as my IDE but am lost without VIM bindings. Anyone else working on this?

**Comment by StefanoBelloni** [comment]
Hallo,
I have forked _codelite_ and started implementing a rudimentary _vim-like bindings for codelite_
[https://github.com/StefanoBelloni/codelite](url)
It is still in an unripe phase.
**Actual Issues:**
    - If I close an editor ( typing :q ) via the IManager, no _wxEVT_ACTIVE_EDITOR_CHANGED_ is sent and _codelite_ crashes.

**Comment by eranif** [comment]
@StefanoBelloni how do you close the editor?

**Comment by eranif** [comment]
@StefanoBelloni I found this method:
```C++
bool VimCommand::OnReturnDown(IEditor **editor, IManager *manager)
```
which in turn calls for `IManager::CloseEditor` (which should work), however, I am lacking context here: can you confirm that `*editor` is not NULL? can you confirm that `manager` is not NULL? (BTW, you can ```C++
IManager* manager = clGetManager();
IEditor* editor = clGetManager()->GetActiveEditor();
```

**Comment by StefanoBelloni** [comment]
Hallo,

Thanks for the quick replay.
I do not understand, why it is crashing. 
If I have two editors-tab open,and a close one with the `IManager::CloseEditor` method, I get the editor to be closed, but no ` wxEVT_ACTIVE_EDITOR_CHANGED` is sent, and consequentially in the method
`void VimManager::OnEditorChanged(wxCommandEvent &event)`
the text controller of the new editor is not connected to the events `wxEVT_CHAR` and `wxEVT_KEY_DOWN`. 
when the other editor is displayed and I press `ESCAPE`, it crashes 
in the method 
` bool QuickFindBar::DoShow(bool s, const wxString& findWhat, bool replaceBar)`
`676├───────> m_sci->SetFocus();`
I guess because the `ESCAPE` try to hide the **quickfindbar**, but its editor has been deleted.

For now as a workaround, when the user pressed _:q_, I simulate the _Ctrl + W_ with the help of 
`wxUIActionSimulator`. ( I do the same to get the _quickfindbar_, when pressing _'/'_, since I could not find a why to have a pointer to it).

Till now for now this plug-in, I am still working on
- The repetition of the command when pressing '.'
- copy/paste.
- a setting dialog to make it active/inactive.

**Comment by eranif** [comment]
why don't you just debug CodeLite? its not hard
You should also have log in `~/.codelite/crash.log`

**Comment by StefanoBelloni** [comment]
Hi,
I think there is a bug in the function: 
```c++
bool MainBook::ClosePage(IEditor* editor, bool prompt)
```
The boolean variable is not used and the call 
`m_book->DeletePage(pos, false)`
does not leave the event to be propagated. 
I guess it has never been found, since the editor is always closed directly with the method 
`bool Notebook::DeletePage(size_t page, bool notify)`
The following should fix it
file: _mainbook.cpp:1429_
```c++
bool MainBook::ClosePage(IEditor* editor, bool prompt)
{
    wxWindow* page = dynamic_cast<wxWindow*>(editor->GetCtrl());
    if(!page) return false;
    int pos = m_book->GetPageIndex(page);
    return (pos != wxNOT_FOUND) && (m_book->DeletePage(pos, prompt));
}
```
_______________
I would not close the issue yet, since if someone wants to contribute to this _vim-mode implementation_ might find the actual fork quicker.

**Comment by eranif** [comment]
This is now merged into CodeLite (mostly works, still needs to be improved, I am working on it)
