### ISSUE TITLE
Weird appearance of folding area

### ISSUE THREAD

**Issue by slycelote** [eranif/codelite#816]
Here is a small screenshot from Windows 7: http://i.imgur.com/sS1R2mF.png
Those lines don't disappear no matter what theme I choose.
There are no lines in Windows 8.1. Is there some setting I modified by mistake?

**Comment by eranif** [comment]
this is a bug in wxWidgets.
it happens when using screen resolution of 125% and above.
I too also have this same problem, my workaround is to simply hide the folding margin.

settings->global editor preferences->folding

**Comment by slycelote** [comment]
Thanks! Do you have a link to the wxWidgets bug?

**Comment by eranif** [comment]
I will as soon as I will open one...

I also reproduced this bug on wxWidgets samples

**Comment by santo74** [comment]
I'm having this problem on linux too, but even more severe: the folding arrows are almost invisible, which makes it very annoying to fold/unfold.

![codelite_folding_margin](https://cloud.githubusercontent.com/assets/7080464/13173519/3d13233e-d6fe-11e5-8322-4d5e88ded44d.png)


This happens on Linux Mint with the Mate desktop.
When I switch to Cinnamon, everything is ok.

**Comment by eranif** [comment]
This is a wxWidgets bug.
Is this a self compiled version of CodeLite?

Also, you can disable the folding margin from: Settings->Preferences->Folding->Display folding margin

NOTE: this does not mean that foldings are disabled, you just don't have the margin with the arrows to click on. You can still fold using the keyboard: `Alt+RIGHT ARROW`

**Comment by santo74** [comment]
Yes, I understand this is a wxWidgets bug, but the ticket dates from july 2015 so I just wanted to inform you that the bug is still an issue.
Also, until now I always worked with Cinnamon onLinux where I don't see this behaviour, but recently I switched to Mate where I first noticed it so I thought it might be interesting to know it isn't happening on Cinnamon.

BTW, I haven't seen this problem on my Windows 7 system.
