### ISSUE TITLE
Goto Declaration or Implementation of Structure Does Not Move Cursor

### ISSUE THREAD

**Issue by samuel-gh** [eranif/codelite#869]
If you right click on a structure type and choose "Goto Declaration" or "Goto Implementation" CodeLite will take you to the structure's type definition, but it doesn't move the cursor to the line of the definition. This is not the case for functions and #define constants, which work as expected. The problem is frustrating because if you Goto Declaration and then press the up or down arrows you are taken to the beginning of the current file and have essentially lost your location in the file.

Reproduced with CodeLite 8.0 on 64-bit Windows 7.

Example to reproduce:

main.h:

typedef struct _tagExample_t
{
    int a;
} Example_t;

main.c:

#include "main.h"

void main(void)
{
    Example_t myexample;
}

Put the cursor on Example_t in main(), right click, and choose "Goto Declaration" or "Goto Implementation".

**Comment by samuel-gh** [comment]
Also reproduced in CodeLite 8.1 on 64-bit Windows 7.

**Comment by gbuntu127** [comment]
It is still reproduced in Codelite 9.0.0 on Ubuntu 14.04. For my case, The "goto declaration" or "goto implementation" function can goto the right file, but sometimes the cursor is at wrong location (most of the time at the bottom of the file if code is folded). It seems to be related to code folding because when the code is not folded, the cursor is at the correct location. In contrast, when code is folded, 90% chance the cursor is at the wrong location.

**Comment by eranif** [comment]
As you can see the bug is still opened... it was not fixed

**Comment by gbuntu127** [comment]
Thank you for your effort!
