### ISSUE TITLE
Problem with gtk overlay scrollbars

### ISSUE THREAD

**Issue by patlefort** [eranif/codelite#887]
I want to report a problem and how I got around it. I recently updated from Fedora 21 to 22 and I noticed that codelite was running very slowly, everything was sluggish especially when ctrl+tabbing. If I ctrl-tabbed multiple time too fast, the file list window would remain visible and I would be forced to double click a file. I turned off the overlay scrollbars and it seem to have fixed the problem. The GTK overlay scrollbars are new in fedora 22 and they don't seem to work well with codelite.

How I got around it:
I simply added the line "GTK_OVERLAY_SCROLLING=0" in "/etc/environment" to disable them everywhere since I don't like them anyway.

**Comment by eranif** [comment]
Which version of CodeLite did you use?

**Comment by patlefort** [comment]
I used version 8.1 and I also tried the development version from august 6. I am running Fedora 22 all up to date with XFCE and nvidia proprietary drivers. I tried changing font anti-aliasing, I tried turning on and off desktop composition.

**Comment by eranif** [comment]
I am asking because this seems like a wxWidgets issue (the editing control is based on wxStyledTextCtrl and the scrollbars are handled by wxWidgets)

One last thing before we move this to wxWidgets tracker: can you disable the option from: 
`Settings->Global Editor Preferences->Editor->Caret and scrolling->Auto adjust horizontal scrollbar width` and see if this makes any difference

Thanks

**Comment by patlefort** [comment]
Same problem with that option enabled or disabled.

**Comment by eranif** [comment]
Thanks, will report this to the wxWidgets team
