### ISSUE TITLE
missing data in Locals/Watches windows

### ISSUE THREAD

**Issue by tomekjaworski** [eranif/codelite#906]
A certain ranges of  uint8_t (haven't tested for other types) are not shown in debug windows.

![gdb_err](https://cloud.githubusercontent.com/assets/14040326/9567355/f897c70e-4f27-11e5-9393-d9963ccd88b6.png)

However they are properly returned by the gdb:
DEBUG>>00008605^done,value="0 '\\000'"
DEBUG>>00008606^done,value="0 '\\000'"
DEBUG>>00008607^done,value="252 '\\374'"
DEBUG>>00008608^done,value="4 '\\004'"
DEBUG>>00008609^done,value="244 '\\364'"
DEBUG>>00008610^done,value="20 '\\024'"
DEBUG>>00008611^done,value="212 '\\324'"
DEBUG>>00008612^done,value="84 'T'"
DEBUG>>00008613^done,value="84 'T'"
DEBUG>>00008614^done,value="84 'T'"
DEBUG>>00008615^done,value="84 'T'"

**Comment by eranif** [comment]
Do you have a code snippet to test this?

**Comment by eranif** [comment]
Ping

**Comment by Havoc2** [comment]
I can confirm this bug. Here's a screenshot and the minimal code example I used to replicate this bug:

![locals](https://cloud.githubusercontent.com/assets/12006431/10228225/d2e76fd8-6871-11e5-995c-df5f2a354e38.png)

```cpp
#include <cstdint>
#include <iostream>
#include <vector>

int main(int argc, char* argv[])
{
    std::vector<std::uint32_t> data(256, 0);
    
    for (std::uint32_t index = 0; index < 256; ++index)
    {
        data[index] = index;
        
        std::cout << "data[" << index << "]: " << data[index] << std::endl;
    }
    
    return 0;
}
```

**Comment by eranif** [comment]
This seems to be a gdb bug... because of the number of commands that CodeLite is sending to gdb
In the above example, CodeLite sending 256 commands of the following format:

`-var-evaluate-expression <var-name>`

I am able to reproduce this bug, _however_ if I enable debugger logging, the problem goes away. I suspect that the micro second that CodeLite needs to write down to the log give the gdb server enough time to process the command
