### ISSUE TITLE
Crosscompilation from Linux to Windows: Windres

### ISSUE THREAD

**Issue by DeXP** [eranif/codelite#907]
I'm crosscompile my project from Linux to Windows. If I compile it in Windows - all is ok, application have the compiled in icon. But if I compile it in Linux - it ignores my .rc-file and does not invokes windres at all.

**Comment by eranif** [comment]
This is because the generated `Makefile` simply ignores `.rc` files on Linux / OSX. This is because in 99% of the cases it will trigger an error if CodeLite will attempt to compile the `.rc` file on non Windows machines.

You can overcome this by adding a custom makefile rule to the project configuration, from:
`project settings->customize->custom makefile rules`

In the `Dependencies` field set: `win_resources.rc.o` (rename `win_resources.rc` to the actual file name)
in the `Rule action`:
```Makefile```
win_resources.rc.o:
	$(RcCompilerName) -i win_resources.rc --use-temp-file --define __WXMSW__ --define _UNICODE --include-dir D:/src/wxWidgets/lib/gcc_dll/mswu --include-dir D:/src/wxWidgets/include --define WXUSINGDLL    -o win_resources.rc.o
```
In the "Rule Action" I set some example values that fit my setup, you should use the ones that matches your configuration

The above rule will generate a `win_resources.rc.o` from `win_resources.rc` file, however, you still need to tell CodeLite to link against this object file, this is done from:
`project settings->linker->linker options` and add the object name, here is how my example adds the resource file:

`$(shell wx-config --libs --debug);-mwindows;win_resources.rc.o`

**Comment by DeXP** [comment]
Great thank you, eranif!
