### ISSUE TITLE
Editor Docking

### ISSUE THREAD

**Issue by prollings** [eranif/codelite#974]
Reimplement multi-editor docking.
The detach window process is no where near as handy.

**Comment by eranif** [comment]
This one is really not a high priority for me and requires a lot of development.
Closing this feature as I don't think I will be implementing it in the near future. Pull requests with an implementation for this are highly appreciated

**Comment by Sod-Almighty** [comment]
What is the point of having a detach facility if you can never, EVER dock the panels again? One is simply left with half a dozen random floating windows, and that is stupid.

At the very least, if you have no intention of fixing this bug which has existed since.....2017 I think? Then at least removing the useless "detach" facility would save people time trying to figure out how to use this broken interface.
