### ISSUE TITLE
Build error parser doesn't work for custom makefile project

### ISSUE THREAD

**Issue by ovk** [eranif/codelite#981]
I have a project which is built by running a Python script that eventually runs Visual C++ 2012. I created new custom makefile project in the CodeLite. I set *Compiler* property in the *General* group of project settings to Visual C++ 12. I also configured my custom build command in project settings.

However, when my project built with some errors, CodeLite doesn't seem to detect them. It always shows `0 errors, 0 warnings` at the bottom of my build log and no errors are marked as such.

I've tried different patterns (which I tested with RegExp tester) in the build settings for Visual C++ 12 but this doesn't help.

CodeLite version: 9.0.1
OS: Windows 10

**Comment by mtangoo** [comment]
Post your makefile as well as the python script.
Its hard to just blind guess what's happening at your machine

**Comment by eranif** [comment]
@ovk can you post your build log?

**Comment by ovk** [comment]
@mtangoo unfortunately I can't post all project's build scripts here. But I doubt it matters, because it just invokes Visual Studio eventually and produces usual VS build log.

@eranif I posted build log here: http://pastebin.com/jLrt20BT

In addition to the built-in VS C++ 12 parser patterns I tried to use this: `(.+)\((\d+)\): error.+`

**Comment by mtangoo** [comment]
do that script work if manually invoked?

**Comment by ovk** [comment]
@mtangoo the role of the custom build script is just to generate a Visual Studio solution and run MSBuild against it. So the actual build is performed by Visual Studio and all output is normal Visual Studio output. I attached the build output in my previous message so as you can see it is just a usual VS build log. It contains some compilation errors, but CodeLite doesn't "see" them.

**Comment by mtangoo** [comment]
So the issue is CL saying 0 errors but everything else is fine?

**Comment by ovk** [comment]
Well, as you can see in the end of the build log there are a lot of warnings and errors:

    14 Warning(s)
    88 Error(s)

However, the lines in the build log containing errors are not marked with different color and I can't click them to open source file on line containing error. 

In addition, the last line (appended by CodeLite) says there no any errors/warnings:

    ====0 errors, 0 warnings, total time: 00:00:22 seconds====

Apart from that everything else is fine. I can build and run my project from CodeLite.

**Comment by eranif** [comment]
@ovk this is not a bug but simply a case of wrong regexes used
* make sure that in your project settings, the selected compiler is `Visual C++ 12` (or the equivalent)
* If the builtin regexs are not working, use this one:
` (\d+\>)([a-zA-Z:]{0,2}[ \\\w\.0-9_/\+\-]+ *)\(\d+\):[ ]*error` for errors

Instead of using 3rd part tools for testing the regexes, try using CodeLite's regex (after all, the Find feature of CodeLite is using the same regex engine as the build parsing)

**Comment by ovk** [comment]
@eranif both regular expressions (the one I posted and yours) work fine when I try them using Find in CodeLite:
![regexptest](https://cloud.githubusercontent.com/assets/693072/10680470/1ee6b5e2-78ee-11e5-99d0-8dae1ec56baf.png)

However, CodeLite still doesn't see errors in the build log.

Here is my project's settings:
![projectsettings](https://cloud.githubusercontent.com/assets/693072/10680478/3a931e20-78ee-11e5-9755-1e2c0fd6280d.png)

And Build Settings:
![buildsettings](https://cloud.githubusercontent.com/assets/693072/10680488/438fb484-78ee-11e5-8d5c-27edad6594e0.png)

**Comment by eranif** [comment]
@ovk , looking at the **Build** tab, all I can see is that CodeLite is running a command which ends 8-10 lines later. Can you please paste here the entire build output as it appears in the **Build** tab in a text format (i.e. no screenshots)

**Comment by ovk** [comment]
@eranif I posted it already: http://pastebin.com/jLrt20BT 

That is the exact build output I copied from the Built tab.

**Comment by eranif** [comment]
@ovk  I haven't been able to reproduce this as it works for me (I am actually using custom build to build CodeLite /w CMake on OSX and Linux
I also use VC++ on Window for my daily job with custom build which also works...

I will need a sample project that shows the problems otherwise, you will have to debug this one yourself

**Comment by ovk** [comment]
@eranif  I created a test project to demonstrate the issue. The project only contains a text file called `BuildLog.txt` containing some errors from VC++ log, and it contains file `build.bat` which reads the `BuildLog.txt` and prints to standard output,

![bug](https://cloud.githubusercontent.com/assets/693072/10711033/7c232d58-7a3d-11e5-9bb3-f21da71ebd97.png)

As you can see from this screenshot, your regexp works perfectly fine when I run it from inside CodeLite against `BuildLog.txt` file. However, CodeLite doesn't detect any errors as you can see in the *Build* tab.

Here is link to the test project: https://www.dropbox.com/s/hlfeojjkkeqhr31/test.zip?dl=0

**Comment by eranif** [comment]
thank you for taking the time to make this sample project.
using this sample project, I will also be able to test this on Linux (I am currently on a business trip in the US with access to Linux laptop only)

**Comment by eranif** [comment]
@ovk we were both correct.
There seems to be a missing flag in the build parser regex generator that did not support the regex special chars (`\w \d` etc) adding this flag fixes the problem.

however, you can alter your regex to work with the current build of CodeLite you have and it will also work, instead of the suggested regexes, use this:

`([0-9]+\>)([a-zA-Z:]{0,2}[ \\a-zA-Z\.0-9_/\+\-]+ *)\(([0-9])+\):[ ]*error`
As the file name index, set `2` and as the line number index use `3`

this will capture your build output
I am also committing a fix that will enable the regex special chars when it comes to parsing build output
